In [1]:
import numpy as np
import pandas as pd

In [100]:
ind_chd = pd.read_csv("data/ind_house_chd.csv")
df = ind_chd.copy()

In [101]:
pd.options.display.max_columns = None

In [102]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,noOfFloor,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7 Bedrooms,7 Bathrooms,3+ Balconies,Servant Room,North-West,2 Floors,Others,10+ Year Old,Marble,NaN,Semifurnished,40.0 Feet,"3 Covered, 3 Open","Municipal corporation,24*7 Water",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28 Cr
1,V75627519,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room,South,1 Floors,Main Road,10+ Year Old,Others,NaN,Unfurnished,40.0 Feet,"1 Covered, 1 Open",Municipal corporation,NaN,Yes,NaN,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14 Cr
2,P75122867,6Bedrooms 6Baths,Independent House/Villa for Sale,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6 Bedrooms,6 Bathrooms,2 Balconies,NaN,South,2 Floors,NaN,1 to 5 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We have a house/villa available for sale in mo...,[],NaN,2.5 Cr
3,W75661879,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others",NaN,2 Floors,"Pool,Club,Others,Sea facing,Main Road,Park/Garden",0 to 1 Year Old,Others,Yes,Furnished,NaN,"1 Covered, 1 Open",24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.65 Cr
4,P75385469,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3 Bedrooms,3 Bathrooms,1 Balcony,NaN,North-West,2 Floors,Park/Garden,Within 3 months,Ceramic,Yes,Semifurnished,30.0 Feet,"1 Covered, 1 Open",Borewell/Tank,NaN,NaN,NaN,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",58.9 Lac

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1208 entries, 0 to 1207
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_id         1208 non-null   object
 1   property_name       1208 non-null   object
 2   property_type       1208 non-null   object
 3   link                1208 non-null   object
 4   Society             77 non-null     object
 5   address1            1208 non-null   object
 6   address2            1208 non-null   object
 7   PricePerUnit        1207 non-null   object
 8   area                1208 non-null   object
 9   area_unit           1208 non-null   object
 10  bedRoom             1208 non-null   object
 11  bathroom            1208 non-null   object
 12  balcony             1208 non-null   object
 13  additionalRoom      803 non-null    object
 14  facing              861 non-null    object
 15  noOfFloor           1145 non-null   object
 16  Overlooking         712 non-null    object
 17  agePossession       1208 non-null   object
 18  Flooring            766 non-null    object
 19  GatedCommunity      286 non-null    object
 20  Furnishing          1055 non-null   object
 21  RoadFacing          516 non-null    object
 22  Parking             983 non-null    object
 23  WaterSource         887 non-null    object
 24  PowerBackup         190 non-null    object
 25  WheelChairFriendly  389 non-null    object
 26  PetFriendly         518 non-null    object
 27  description         1208 non-null   object
 28  furnishDetails      626 non-null    object
 29  features            932 non-null    object
 30  price               1208 non-null   object
dtypes: object(31)
memory usage: 292.7+ KB

In [104]:
pd.options.display.max_rows = None

### Water Source

In [105]:
df['WaterSource'].value_counts()

WaterSource
Municipal corporation                             312
Municipal corporation,24*7 Water                  307
24*7 Water                                        110
Municipal corporation,Borewell/Tank                43
Municipal corporation,Borewell/Tank,24*7 Water     41
24*7 Water,Municipal corporation                   22
Borewell/Tank,24*7 Water                           19
Borewell/Tank                                      13
24*7 Water,Borewell/Tank,Municipal corporation      6
Municipal corporation,24*7 Water,Borewell/Tank      5
Borewell/Tank,Municipal corporation,24*7 Water      4
24*7 Water,Borewell/Tank                            3
24*7 Water,Municipal corporation,Borewell/Tank      2
Name: count, dtype: int64

In [106]:
water_source = df['WaterSource'][:]

In [107]:
def water_source_func(x):
    if pd.notna(x):
        temp = sorted(x.split(','))
        return ','.join(temp)
    return x

In [108]:
water_source.apply(water_source_func).value_counts()

WaterSource
24*7 Water,Municipal corporation                  329
Municipal corporation                             312
24*7 Water                                        110
24*7 Water,Borewell/Tank,Municipal corporation     58
Borewell/Tank,Municipal corporation                43
24*7 Water,Borewell/Tank                           22
Borewell/Tank                                      13
Name: count, dtype: int64

In [109]:
df['WaterSource'] = df['WaterSource'].apply(water_source_func)

### bedRoom

In [110]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     306
6 Bedrooms     222
5 Bedrooms     222
3 Bedrooms     180
9 Bedrooms     101
7 Bedrooms      71
8 Bedrooms      55
2 Bedrooms      35
10 Bedrooms      7
1 Bedroom        6
12 Bedrooms      2
20 Bedrooms      1
Name: count, dtype: int64

In [111]:
def bedroom_func(x):
    if pd.notna(x):
        return x.split(' ')[0]
    return x

In [112]:
df['bedRoom'] = df['bedRoom'].apply(bedroom_func).astype(int)

### bathRoom

In [113]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     364
3 Bathrooms     227
5 Bathrooms     184
6 Bathrooms     154
2 Bathrooms      84
7 Bathrooms      67
9 Bathrooms      67
8 Bathrooms      38
1 Bathroom       17
10 Bathrooms      3
12 Bathrooms      2
18 Bathrooms      1
Name: count, dtype: int64

In [114]:
df['bathroom'].isna().sum()

0

In [115]:
def bathroom_func(x):
    if pd.notna(x):
        return x.split(' ')[0]
    return x

In [116]:
df['bathroom'] = df['bathroom'].apply(bedroom_func).astype(int)

### balcony

In [117]:
df['balcony'].value_counts()

balcony
3+ Balconies    475
2 Balconies     364
3 Balconies     255
No Balcony       59
1 Balcony        55
Name: count, dtype: int64

In [118]:
def balcony_func(x):
    if pd.notna(x):
        val = x.split(' ')[0]
        if val == 'No':
            return '0'
        elif val == '3+':
            return '4'
        else:
            return val
    return x

In [119]:
df['balcony'] = df['balcony'].apply(balcony_func).astype(int)

### Facing

In [120]:
df['facing'].value_counts()

facing
East          211
North-East    204
North-West    139
North         116
South-East    108
South-West     43
South          22
West           18
Name: count, dtype: int64

In [121]:
df['facing'].isna().sum()

347

### Floors

In [122]:
df[df['noOfFloor'] == '03 Floors']

Empty DataFrame
Columns: [property_id, property_name, property_type, link, Society, address1, address2, PricePerUnit, area, area_unit, bedRoom, bathroom, balcony, additionalRoom, facing, noOfFloor, Overlooking, agePossession, Flooring, GatedCommunity, Furnishing, RoadFacing, Parking, WaterSource, PowerBackup, WheelChairFriendly, PetFriendly, description, furnishDetails, features, price]
Index: []

In [26]:
df.loc[322]

property_id                                                   Z71734792
property_name                                         10Bedrooms 7Baths
property_type                          Independent House/Villa for Sale
link                  https://www.99acres.com/10-bhk-bedroom-indepen...
Society                                                             NaN
address1                              Sector 125 Mohali, Mohali, Punjab
address2                         263, Sector 125 Mohali, Mohali, Punjab
PricePerUnit                                          86,666 per sq.ft.
area                                 Plot area 150(13.94 sq.m.)  sq.ft.
area_unit                                                        sq.ft.
bedRoom                                                              10
bathroom                                                              7
balcony                                                               4
additionalRoom                                                   Others
facing                                                       North-East
noOfFloor                                                     03 Floors
Overlooking                                                   Main Road
agePossession                                           1 to 5 Year Old
Flooring                                                         Marble
GatedCommunity                                                      NaN
Furnishing                                                Semifurnished
RoadFacing                                                          NaN
Parking                                               1 Covered, 2 Open
WaterSource                                               Borewell/Tank
PowerBackup                                                         NaN
WheelChairFriendly                                                  Yes
PetFriendly                                                         Yes
description           Stunning independent house for sale in sector ...
furnishDetails        ['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...
features                                                            NaN
price                                                            1.3 Cr
Name: 322, dtype: object

In [123]:
df['noOfFloor'].value_counts()

noOfFloor
2 Floors    556
3 Floors    391
1 Floors    190
4 Floors      6
5 Floors      1
0 Floors      1
Name: count, dtype: int64

In [124]:
#df[df['noOfFloor'] == '22 Floors']

In [125]:
#df['noOfFloor'].loc[172]

In [126]:
#df.drop(172,inplace = True)

In [127]:
df['noOfFloor'].isna().sum()

63

In [128]:
df[df['noOfFloor'].isna()]

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,noOfFloor,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
25,S75938777,3Bedrooms 2Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Khuda Ali Sher, Chandigarh, India","883, Khuda Ali Sher, Chandigarh, India","7,000 per sq.ft.",Plot area 1000(92.9 sq.m.) sq.ft.,sq.ft.,3,2,1,NaN,East,NaN,NaN,Within 3 months,NaN,NaN,Semifurnished,NaN,NaN,NaN,Full,NaN,Yes,"20*10 showroom on main road, corner house, ful...","['3 Fan', '1 Exhaust Fan', '6 Light', 'No AC',...",NaN,70 Lac
123,W76547977,5Bedrooms 5Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","54,000 per sq.ft.",Plot area 5000(464.52 sq.m.) sq.ft.,sq.ft.,5,5,4,"Servant Room,Pooja Room",North-East,NaN,NaN,1 to 5 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,NaN,Newly built kothi \nItalian marble \nModular k...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...",NaN,27 Cr
124,H76492941,5Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 9 Chandigarh, Chandigarh, India","Sector 9 Chandigarh, Chandigarh, India","31,481 per sq.ft.",Plot area 27000(2508.38 sq.m.) sq.ft.,sq.ft.,5,4,4,Servant Room,South-West,NaN,NaN,5 to 10 Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,Good location \nReady to move \nBeautiful lawn,NaN,NaN,85 Cr
125,Q76490037,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 36 Chandigarh, Chandigarh, India","Sector 36 Chandigarh, Chandigarh, India","31,111 per sq.ft.",Plot area 11250(1045.16 sq.m.) sq.ft.,sq.ft.,4,4,4,NaN,NaN,NaN,NaN,10+ Year Old,NaN,NaN,Unfurnished,NaN,"3 Covered, 3 Open",NaN,NaN,NaN,NaN,Mud house \nCorner house \nGood location,NaN,NaN,35 Cr
126,X76475951,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","34,000 per sq.ft.",Plot area 5000(464.52 sq.m.) sq.ft.,sq.ft.,4,4,4,Servant Room,NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,Corner house \nFacing park \nReady to move,NaN,NaN,17 Cr
127,Z76475379,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 35 Chandigarh, Chandigarh, India","Sector 35 Chandigarh, Chandigarh, India","37,777 per sq.ft.",Plot area 4500(418.06 sq.m.) sq.ft.,sq.ft.,4,4,4,Servant Room,NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,Beautiful house \nNice sector \nNear market,NaN,NaN,17 Cr
128,S76475221,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 35 Chandigarh, Chandigarh, India","Sector 35 Chandigarh, Chandigarh, India","26,666 per sq.ft.",Plot area 4500(418.06 sq.m.) sq.ft.,sq.ft.,4,4,4,Servant Room,NaN,NaN,NaN,10+ Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,Good location \nNice sec \nNear hospital,NaN,NaN,12 Cr
129,N76475113,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 35 Chandigarh, Chandigarh, India","Sector 35 Chandigarh, Chandigarh, India","25,555 per sq.ft.",Plot area 4500(418.06 sq.m.) sq.ft.,sq.ft.,4,4,4,Servant Room,NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,Good location \nNice house \nGenuine price,NaN,NaN,11.5 Cr
130,Q76474745,5Bedrooms 5Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","38,888 per sq.ft.",Plot area 4500(418.06 sq.m.) sq.ft.,sq.ft.,5,5,4,NaN,NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B road \nGood sec near hospital \nSchool nearb...,[],NaN,17.5 Cr
131,P76474415,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 8 Chandigarh, Chandigarh, India","Sector 8 Chandigarh, Chandigarh, India","36,666 per sq.ft.",Plot area 4500(418.06 sq.m.) sq.ft.,sq.ft.,3,3,3,NaN,NaN,NaN,NaN,10+ Year Old,NaN,NaN,Unfurnished,NaN,NaN,NaN,NaN,NaN,NaN,One of the best sec \nNear school,NaN,NaN,16.5 Cr
134,N76473485,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 8 Chandigarh, Chandigarh, India","Sector 8 Chandigarh, Chandigarh, India","35,555 per sq.ft.",Plot area 9000(836.13 sq.m.) sq.ft.,sq.ft.,4,4,4,Pooja Room,North,NaN,Park/Garden,10+ Year Old,NaN,NaN,Unfurnished,NaN,"1 Covered, 1 Open",NaN,NaN,NaN,NaN,Good location \nBest sector \nFacing park \nMa...,NaN,NaN,32 Cr
163,T76466939,4Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 36 Chandigarh, Chandigarh, India","Sector 36 Chandigarh, Chandigarh, India","2,41,379 per sq.yards",Plot area 580(484.95 sq.m.) sq.yards,sq.yards,4,3,2,NaN,North-West,NaN,NaN,10+ Year Old,NaN,NaN,Unfurnished,NaN,"2 Covered, 2 Open",NaN,NaN,NaN,NaN,Are you planning to buy your dream home? You c...,NaN,NaN,14 Cr
173,S76581923,5Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 19 Chandigarh, Chandigarh, India","Sector 19 Chandigarh, Chandigarh, India","14,00,00,000 per kanal",Plot area 2(1011.71 sq.m.) kanal,kanal,5,4,3,NaN,South-East,NaN,NaN,0 to 1 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Brand new, triple storey built, 2 kanal house ...",[],"['Private Garden / Terrace', 'Water Storage', ...",28 Cr
196,U74749567,5Bedrooms 5Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 2 Chandigarh, Chandigarh, India","Sector 2 Chandigarh, Chandigarh, India","13,00,00,000 per kanal",Plot area 4(2023.43 sq.m.) kanal,kanal,5,5,4,"Pooja Room,Study Room,Others,Servant Room",North,NaN,Main Road,10+ Year Old,Concrete,NaN,Semifurnished,NaN,"2 Covered, 2 Open",Municipal corporation,Partial,Yes,Yes,Four kanal house sector 2 chandigarh \n2000 sq...,"['1 Bed', '1 Wardrobe', '1 Fan', '1 Sofa', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...",60 Cr
289,S75579921,5Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 16 Chandigarh, Chandigarh, India","Sector 16 Chandigarh, Chandigarh, India","2,40,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,5,4,3,NaN,NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,On the lookout for a spacious house in chandig...,[],NaN,6.5 Cr
295,I75579559,5Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,"Sector 35 Chandigarh, Chandigarh, India","Sector 35 Chandigarh, Chandigarh, India","2,20,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,5,4,3,NaN,NaN,NaN,NaN,10+ Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Planning to buy an individual house in chandig...,[],NaN,5.5 Cr
405,I76531955,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","2,56,000 per sq.ft.",Plot area 250(23.23 sq.m.) sq.ft.,sq.ft.,4,4,4,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,10 marla kothi for sale in sector 33 chandigarh,"['1 Wardrobe', '1 Bed', '1 Fan', '1 Light', '1...","['High Ceiling Height', 'Water Storage']",6.4 Cr
406,J76531043,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","2,48,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,10 marla kothi for sale in sector 33 chandigarh.,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",6.2 Cr
407,F76523609,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","2,40,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,10 marla kothi for sale in sector 33 chandigarh.,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",6 Cr
408,I76474331,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","3,00,000 per sq.ft.",Plot area 500(46.45 sq.m.) sq.ft.,sq.ft.,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 1 kanal kothi for sale in sector 21 ...,"['1 Bed', '1 Wardrobe', '1 Fan', '1 Light', '1...","['High Ceiling Height', 'Water Storage']",15 Cr
409,Q76472957,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","3,40,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 1 kanal kothi for sale in sector 21 ...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",17 Cr
410,Q76472935,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","3,00,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 1 kanal kothi for sale in sector 21 ...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",15 Cr
411,T76472899,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","3,20,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 1 kanal kothi for sale in sector 21 ...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",16 Cr
412,W76472705,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","3,20,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 10 marla kothi for sale in sector 33...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",8 Cr
413,W76472677,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","32,00,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 10 marla kothi for sale in sector 33...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",80 Cr
414,N76472493,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","3,00,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 10 marla kothi for sale in sector 33...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],7.5 Cr
415,D76472445,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","3,16,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,Brand new 10 marla kothi for sale in sector 33...,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],7.9 Cr
416,C76472271,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,50,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],12.5 Cr
417,G76472229,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,40,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],12 Cr
418,H76472181,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,30,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],11.5 Cr
419,I76472063,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,20,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Store Room,Pooja Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...",['Water Storage'],11 Cr
420,D76472001,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,10,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Study Room,Store Room,Pooja Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",10.5 Cr
421,Z76471957,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,00,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,4,4,4,"Study Room,Store Room,Pooja Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,1 kanal kothi for sale in sector 21 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",10 Cr
422,A76471673,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 22 Chandigarh, Chandigarh, India","Sector 22 Chandigarh, Chandigarh, India","2,20,000 per sq.yards",Plot area 125(104.52 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,5 marla kothi for sale in sector 22 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",2.75 Cr
423,L76471539,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 22 Chandigarh, Chandigarh, India","Sector 22 Chandigarh, Chandigarh, India","2,00,000 per sq.yards",Plot area 125(104.52 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,5 marla kothi for sale in sector 22 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",2.5 Cr
424,K76471347,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 22 Chandigarh, Chandigarh, India","Sector 22 Chandigarh, Chandigarh, India","1,80,000 per sq.yards",Plot area 125(104.52 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,5 marla kothi for sale in sector 22 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",2.25 Cr
425,X76471201,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 22 Chandigarh, Chandigarh, India","Sector 22 Chandigarh, Chandigarh, India","1,60,000 per sq.yards",Plot area 125(104.52 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,5 marla kothi for sale in sector 22 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",2 Cr
426,Y76470769,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 18 Chandigarh, Chandigarh, India","Sector 18 Chandigarh, Chandigarh, India","2,00,000 per sq.yards",Plot area 200(167.23 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,8 marla kothi for sale in sector 18 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",4 Cr
427,G76470695,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 18 Chandigarh, Chandigarh, India","Sector 18 Chandigarh, Chandigarh, India","2,12,500 per sq.yards",Plot area 200(167.23 sq.m.) sq.yards,sq.yards,4,4,3,"Store Room,Study Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,8 marla kothi for sale in sector 18 chandigarh,"['1 Bed', '1 Fan', '1 Light', '1 AC', '1 TV', ...","['High Ceiling Height', 'Water Storage']",4.25 Cr
428,D76468339,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,"Sector 21 Chandigarh, Chandigarh, India","Sector 21 Chandigarh, Chandigarh, India","2,72,000 per sq.yards",Plot area 250(209.03 sq.m.) sq.yards,sq.yards,4,4,4,"Study Room,Store Room",NaN,NaN,NaN,5 to 10 Year Old,NaN,NaN,Furnished,NaN,NaN,NaN,NaN,NaN,Yes,10 marla kothi for sale in sector 21 chandigarh.,"['1 Fan', '1 Light', '1 AC', '1 TV', '1 Curtai...","['High Ceiling Height', 'Water Storage']",6.8 Cr

In [129]:
df['noOfFloor'].fillna(value='2 Floors',inplace = True)

In [130]:
df['noOfFloor'].value_counts()

noOfFloor
2 Floors    619
3 Floors    391
1 Floors    190
4 Floors      6
5 Floors      1
0 Floors      1
Name: count, dtype: int64

In [131]:
def tot_flr(x):
    if pd.notna(x):
        return x.split(' ')[0]
    return x

In [132]:
df['noOfFloor'] = df['noOfFloor'].apply(tot_flr).astype(int)

In [133]:
df.rename(columns={'noOfFloor': 'TotalFloors'},inplace = True)

In [135]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,10+ Year Old,Marble,NaN,Semifurnished,40.0 Feet,"3 Covered, 3 Open","24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28 Cr
1,V75627519,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,10+ Year Old,Others,NaN,Unfurnished,40.0 Feet,"1 Covered, 1 Open",Municipal corporation,NaN,Yes,NaN,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14 Cr
2,P75122867,6Bedrooms 6Baths,Independent House/Villa for Sale,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,1 to 5 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We have a house/villa available for sale in mo...,[],NaN,2.5 Cr
3,W75661879,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Pool,Club,Others,Sea facing,Main Road,Park/Garden",0 to 1 Year Old,Others,Yes,Furnished,NaN,"1 Covered, 1 Open",24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.65 Cr
4,P75385469,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,Within 3 months,Ceramic,Yes,Semifurnished,30.0 Feet,"1 Covered, 1 Open",Borewell/Tank,NaN,NaN,NaN,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",58.9 Lac

### Overlooking

In [136]:
df['Overlooking'].value_counts()

Overlooking
Others                                               245
Park/Garden                                          148
Main Road                                            112
Park/Garden,Main Road                                 51
Park/Garden,Others                                    39
Main Road,Others                                      15
Park/Garden,Main Road,Others                          15
Main Road,Park/Garden                                 13
Others,Main Road                                      12
Park/Garden,Main Road,Club,Others                     10
Others,Park/Garden                                     6
Park/Garden,Others,Main Road                           4
Pool,Park/Garden,Club,Main Road                        4
Park/Garden,Main Road,Club                             3
Park/Garden,Club                                       3
Main Road,Park/Garden,Others                           2
Main Road,Club,Park/Garden,Pool                        2
Park/Garden,Club,Main Road                             2
Park/Garden,Club,Pool                                  2
Park/Garden,Club,Others                                2
Others,Main Road,Park/Garden                           1
Park/Garden,Club,Main Road,Others                      1
Park/Garden,Pool                                       1
Others,Park/Garden,Main Road                           1
Pool,Park/Garden,Club,Sea facing,Main Road,Others      1
Pool,Park/Garden,Club,Main Road,Others                 1
Pool,Main Road,Club,Park/Garden                        1
Park/Garden,Main Road,Club,Pool,Others                 1
Park/Garden,Main Road,Pool,Others                      1
Sea facing,Main Road                                   1
Pool,Park/Garden,Others,Main Road                      1
Pool,Park/Garden,Club,Others,Main Road,Sea facing      1
Park/Garden,Club,Main Road,Pool,Others                 1
Park/Garden,Club,Sea facing,Others,Main Road,Pool      1
Main Road,Park/Garden,Club                             1
Pool,Park/Garden,Main Road,Club                        1
Club                                                   1
Main Road,Club,Park/Garden                             1
Pool,Park/Garden,Club                                  1
Pool,Park/Garden                                       1
Pool,Club,Others,Sea facing,Main Road,Park/Garden      1
Park/Garden,Main Road,Pool,Sea facing                  1
Name: count, dtype: int64

In [137]:
def overlooking_func(x):
    if pd.notna(x):
        temp = sorted(x.split(','))
        return ','.join(temp)
    return x

In [138]:
df['Overlooking'] = df['Overlooking'].apply(overlooking_func)

In [139]:
df['Overlooking'].value_counts()

Overlooking
Others                                               245
Park/Garden                                          148
Main Road                                            112
Main Road,Park/Garden                                 64
Others,Park/Garden                                    45
Main Road,Others                                      27
Main Road,Others,Park/Garden                          23
Club,Main Road,Others,Park/Garden                     11
Club,Main Road,Park/Garden,Pool                        8
Club,Main Road,Park/Garden                             7
Club,Main Road,Others,Park/Garden,Pool,Sea facing      4
Club,Park/Garden,Pool                                  3
Club,Park/Garden                                       3
Club,Main Road,Others,Park/Garden,Pool                 3
Park/Garden,Pool                                       2
Main Road,Others,Park/Garden,Pool                      2
Club,Others,Park/Garden                                2
Club                                                   1
Main Road,Sea facing                                   1
Main Road,Park/Garden,Pool,Sea facing                  1
Name: count, dtype: int64

In [140]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,10+ Year Old,Marble,NaN,Semifurnished,40.0 Feet,"3 Covered, 3 Open","24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28 Cr
1,V75627519,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,10+ Year Old,Others,NaN,Unfurnished,40.0 Feet,"1 Covered, 1 Open",Municipal corporation,NaN,Yes,NaN,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14 Cr
2,P75122867,6Bedrooms 6Baths,Independent House/Villa for Sale,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,1 to 5 Year Old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We have a house/villa available for sale in mo...,[],NaN,2.5 Cr
3,W75661879,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Club,Main Road,Others,Park/Garden,Pool,Sea facing",0 to 1 Year Old,Others,Yes,Furnished,NaN,"1 Covered, 1 Open",24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.65 Cr
4,P75385469,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,Within 3 months,Ceramic,Yes,Semifurnished,30.0 Feet,"1 Covered, 1 Open",Borewell/Tank,NaN,NaN,NaN,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",58.9 Lac

In [141]:
df['Overlooking'].isna().sum()

496

### agePossession

In [142]:
df['agePossession'].value_counts()

agePossession
10+ Year Old          740
5 to 10 Year Old      176
0 to 1 Year Old       169
1 to 5 Year Old        95
Within 3 months         7
Within 6 months         6
Under Construction      5
By 2024                 3
undefined               3
Apr 2025                1
Oct 2024                1
Dec 2025                1
Jul 2026                1
Name: count, dtype: int64

In [143]:
def age_possess_func(x):
    if pd.notna(x):
        if x == '10+ Year Old':
            return 'Old'
        elif x == '5 to 10 Year Old':
            return 'ModOld'
        elif x == '1 to 5 Year Old':
            return 'RelNew'
        elif x == '0 to 1 Year Old':
            return 'New'
        else:
            return 'UndConst'
    return x

In [144]:
df['agePossession'] = df['agePossession'].apply(age_possess_func)

In [145]:
df['agePossession'].value_counts()

agePossession
Old         740
ModOld      176
New         169
RelNew       95
UndConst     28
Name: count, dtype: int64

### Flooring

In [146]:
df['Flooring'].value_counts()

Flooring
Marble               356
Vitrified            210
Mosaic                53
Others                35
Concrete              32
Ceramic               28
Granite               22
Wood                  12
Stone                  7
Cement                 7
Polished concrete      4
Name: count, dtype: int64

In [147]:
df['Flooring'].isna().sum()

442

In [148]:
# will handle missing values later

### GatedCommunity

In [149]:
df['GatedCommunity'].value_counts()

GatedCommunity
Yes    286
Name: count, dtype: int64

In [150]:
df['GatedCommunity'].isna().sum()

922

In [151]:
df['GatedCommunity'].fillna(value = 'No',inplace = True)

In [152]:
df['GatedCommunity'].value_counts()

GatedCommunity
No     922
Yes    286
Name: count, dtype: int64

### PetFriendly

In [153]:
df['PetFriendly'].value_counts()

PetFriendly
Yes    518
Name: count, dtype: int64

In [154]:
df['PetFriendly'].isna().sum()

690

In [155]:
df['PetFriendly'].fillna(value = 'No',inplace = True)

In [156]:
df['PetFriendly'].value_counts()

PetFriendly
No     690
Yes    518
Name: count, dtype: int64

### Furnishing

In [157]:
df['Furnishing'].value_counts()

Furnishing
Unfurnished      582
Semifurnished    393
Furnished         80
Name: count, dtype: int64

In [158]:
df['Furnishing'].isna().sum()

153

In [159]:
### will handle missing value later

### RoadFacing

In [160]:
df['RoadFacing']

0        40.0 Feet
1        40.0 Feet
2              NaN
3              NaN
4        30.0 Feet
5        40.0 Feet
6        60.0 Feet
7              NaN
8              NaN
9              NaN
10             NaN
11             NaN
12             NaN
13             NaN
14             NaN
15             NaN
16             NaN
17       20.0 Feet
18             NaN
19             NaN
20             NaN
21       26.0 Feet
22       40.0 Feet
23             NaN
24             NaN
25             NaN
26       20.0 Feet
27       35.0 Feet
28       40.0 Feet
29             NaN
30       40.0 Feet
31             NaN
32       30.0 Feet
33             NaN
34             NaN
35             NaN
36       20.0 Feet
37             NaN
38             NaN
39             NaN
40             NaN
41             NaN
42             NaN
43             NaN
44             NaN
45             NaN
46       40.0 Feet
47             NaN
48       40.0 Feet
49       40.0 Feet
50       30.0 Feet
51       40.0 Feet
52       40.0 Feet
53             NaN
54             NaN
55             NaN
56       40.0 Feet
57       60.0 Feet
58       40.0 Feet
59             NaN
60             NaN
61             NaN
62             NaN
63             NaN
64             NaN
65       40.0 Feet
66             NaN
67       35.0 Feet
68       25.0 Feet
69       30.0 Feet
70       30.0 Feet
71       40.0 Feet
72       40.0 Feet
73       60.0 Feet
74             NaN
75             NaN
76       40.0 Feet
77       40.0 Feet
78       40.0 Feet
79       30.0 Feet
80       60.0 Feet
81       60.0 Feet
82       40.0 Feet
83             NaN
84             NaN
85             NaN
86       20.0 Feet
87       30.0 Feet
88       30.0 Feet
89       30.0 Feet
90       30.0 Feet
91       30.0 Feet
92       30.0 Feet
93       30.0 Feet
94       30.0 Feet
95       30.0 Feet
96       30.0 Feet
97       35.0 Feet
98             NaN
99       30.0 Feet
100            NaN
101      35.0 Feet
102      25.0 Feet
103      45.0 Feet
104            NaN
105      22.0 Feet
106            NaN
107            NaN
108      60.0 Feet
109            NaN
110            NaN
111            NaN
112            NaN
113            NaN
114            NaN
115            NaN
116            NaN
117            NaN
118            NaN
119            NaN
120            NaN
121            NaN
122            NaN
123            NaN
124            NaN
125            NaN
126            NaN
127            NaN
128            NaN
129            NaN
130            NaN
131            NaN
132            NaN
133            NaN
134            NaN
135      34.0 Feet
136            NaN
137            NaN
138            NaN
139            NaN
140            NaN
141            NaN
142            NaN
143            NaN
144      40.0 Feet
145      40.0 Feet
146      40.0 Feet
147      40.0 Feet
148      40.0 Feet
149      40.0 Feet
150      35.0 Feet
151            NaN
152            NaN
153      40.0 Feet
154      40.0 Feet
155      30.0 Feet
156      35.0 Feet
157      40.0 Feet
158      40.0 Feet
159            NaN
160     200.0 Feet
161            NaN
162            NaN
163            NaN
164      25.0 Feet
165            NaN
166            NaN
167            NaN
168      35.0 Feet
169            NaN
170            NaN
171            NaN
172     100.0 Feet
173            NaN
174            NaN
175      40.0 Feet
176            NaN
177            NaN
178            NaN
179      40.0 Feet
180      40.0 Feet
181      30.0 Feet
182      30.0 Feet
183            NaN
184            NaN
185      60.0 Feet
186      60.0 Feet
187     500.0 Feet
188            NaN
189      60.0 Feet
190      60.0 Feet
191      60.0 Feet
192            NaN
193            NaN
194            NaN
195            NaN
196            NaN
197      60.0 Feet
198      38.0 Feet
199            NaN
200      60.0 Feet
201            NaN
202            NaN
203      60.0 Feet
204            NaN
205            NaN
206     100.0 Feet
207      40.0 Feet
208      30.0 Feet
209      45.0 Feet
210            NaN
211            NaN
212            NaN
213            NaN
214            NaN
215            NaN
216            NaN
217            NaN
218            NaN
219            NaN
220            NaN
221            NaN
222            NaN
223            NaN
224            NaN
225            NaN
226            NaN
227            NaN
228            NaN
229            NaN
230            NaN
231            NaN
232            NaN
233            NaN
234            NaN
235            NaN
236            NaN
237            NaN
238            NaN
239            NaN
240            NaN
241            NaN
242            NaN
243            NaN
244            NaN
245      40.0 Feet
246            NaN
247            NaN
248            NaN
249            NaN
250            NaN
251            NaN
252            NaN
253            NaN
254            NaN
255            NaN
256            NaN
257            NaN
258            NaN
259            NaN
260      30.0 Feet
261      30.0 Feet
262      30.0 Feet
263      30.0 Feet
264     200.0 Feet
265            NaN
266            NaN
267            NaN
268            NaN
269            NaN
270            NaN
271            NaN
272            NaN
273            NaN
274            NaN
275            NaN
276            NaN
277            NaN
278            NaN
279            NaN
280            NaN
281            NaN
282      20.0 Feet
283            NaN
284            NaN
285            NaN
286            NaN
287            NaN
288            NaN
289            NaN
290            NaN
291            NaN
292            NaN
293            NaN
294            NaN
295            NaN
296            NaN
297            NaN
298            NaN
299            NaN
300            NaN
301            NaN
302            NaN
303            NaN
304            NaN
305            NaN
306            NaN
307            NaN
308            NaN
309            NaN
310            NaN
311            NaN
312            NaN
313            NaN
314            NaN
315            NaN
316            NaN
317            NaN
318            NaN
319            NaN
320            NaN
321            NaN
322            NaN
323            NaN
324            NaN
325            NaN
326            NaN
327            NaN
328            NaN
329            NaN
330            NaN
331            NaN
332            NaN
333            NaN
334            NaN
335            NaN
336            NaN
337            NaN
338            NaN
339            NaN
340            NaN
341            NaN
342            NaN
343            NaN
344            NaN
345            NaN
346            NaN
347            NaN
348            NaN
349            NaN
350            NaN
351            NaN
352            NaN
353            NaN
354            NaN
355            NaN
356            NaN
357            NaN
358            NaN
359            NaN
360            NaN
361            NaN
362            NaN
363            NaN
364            NaN
365      40.0 Feet
366            NaN
367            NaN
368            NaN
369            NaN
370            NaN
371            NaN
372            NaN
373            NaN
374            NaN
375            NaN
376            NaN
377            NaN
378            NaN
379            NaN
380            NaN
381            NaN
382            NaN
383            NaN
384            NaN
385            NaN
386            NaN
387            NaN
388            NaN
389            NaN
390            NaN
391            NaN
392            NaN
393            NaN
394            NaN
395            NaN
396            NaN
397            NaN
398            NaN
399            NaN
400      25.0 Feet
401            NaN
402      25.0 Feet
403            NaN
404            NaN
405            NaN
406            NaN
407            NaN
408            NaN
409            NaN
410            NaN
411            NaN
412            NaN
413            NaN
414            NaN
415            NaN
416            NaN
417            NaN
418            NaN
419            NaN
420            NaN
421            NaN
422            NaN
423            NaN
424            NaN
425            NaN
426            NaN
427            NaN
428            NaN
429            NaN
430            NaN
431            NaN
432            NaN
433            NaN
434            NaN
435            NaN
436            NaN
437            NaN
438            NaN
439            NaN
440            NaN
441            NaN
442            NaN
443            NaN
444            NaN
445     100.0 Feet
446     200.0 Feet
447            NaN
448            NaN
449            NaN
450            NaN
451            NaN
452            NaN
453            NaN
454            NaN
455            NaN
456            NaN
457            NaN
458      45.0 Feet
459      25.0 Feet
460            NaN
461      40.0 Feet
462      40.0 Feet
463      40.0 Feet
464      40.0 Feet
465      40.0 Feet
466      40.0 Feet
467      60.0 Feet
468      60.0 Feet
469      60.0 Feet
470      80.0 Feet
471      60.0 Feet
472      60.0 Feet
473      60.0 Feet
474      50.0 Feet
475      60.0 Feet
476      60.0 Feet
477      60.0 Feet
478      60.0 Feet
479      60.0 Feet
480      60.0 Feet
481      60.0 Feet
482      60.0 Feet
483      60.0 Feet
484      60.0 Feet
485      60.0 Feet
486      60.0 Feet
487      60.0 Feet
488      50.0 Feet
489      60.0 Feet
490      60.0 Feet
491      60.0 Feet
492      60.0 Feet
493      60.0 Feet
494      60.0 Feet
495      60.0 Feet
496      50.0 Feet
497      60.0 Feet
498      60.0 Feet
499      60.0 Feet
500      50.0 Feet
501      60.0 Feet
502      60.0 Feet
503      60.0 Feet
504      60.0 Feet
505      50.0 Feet
506      60.0 Feet
507      60.0 Feet
508      50.0 Feet
509      50.0 Feet
510      50.0 Feet
511      50.0 Feet
512      50.0 Feet
513      60.0 Feet
514      60.0 Feet
515      60.0 Feet
516      60.0 Feet
517      60.0 Feet
518      60.0 Feet
519      60.0 Feet
520      60.0 Feet
521      60.0 Feet
522      60.0 Feet
523      60.0 Feet
524      50.0 Feet
525      50.0 Feet
526      50.0 Feet
527      50.0 Feet
528      60.0 Feet
529      50.0 Feet
530      50.0 Feet
531      50.0 Feet
532      60.0 Feet
533      60.0 Feet
534      60.0 Feet
535      50.0 Feet
536      50.0 Feet
537      50.0 Feet
538      50.0 Feet
539      50.0 Feet
540            NaN
541      60.0 Feet
542      60.0 Feet
543      60.0 Feet
544      60.0 Feet
545      60.0 Feet
546      30.0 Feet
547      30.0 Feet
548      30.0 Feet
549      35.0 Feet
550      25.0 Feet
551      25.0 Feet
552      25.0 Feet
553      25.0 Feet
554      25.0 Feet
555      25.0 Feet
556            NaN
557      25.0 Feet
558      25.0 Feet
559      25.0 Feet
560      25.0 Feet
561      30.0 Feet
562      20.0 Feet
563      25.0 Feet
564      20.0 Feet
565      25.0 Feet
566      45.0 Feet
567      50.0 Feet
568            NaN
569      40.0 Feet
570            NaN
571            NaN
572            NaN
573      35.0 Feet
574      36.0 Feet
575      60.0 Feet
576      60.0 Feet
577      60.0 Feet
578      40.0 Feet
579      40.0 Feet
580      25.0 Feet
581      35.0 Feet
582            NaN
583            NaN
584            NaN
585      30.0 Feet
586            NaN
587            NaN
588            NaN
589            NaN
590            NaN
591            NaN
592            NaN
593            NaN
594            NaN
595            NaN
596            NaN
597            NaN
598            NaN
599            NaN
600            NaN
601            NaN
602            NaN
603      40.0 Feet
604      40.0 Feet
605            NaN
606            NaN
607            NaN
608      40.0 Feet
609            NaN
610      40.0 Feet
611            NaN
612            NaN
613            NaN
614            NaN
615            NaN
616      40.0 Feet
617      40.0 Feet
618      40.0 Feet
619      40.0 Feet
620            NaN
621            NaN
622      20.0 Feet
623      40.0 Feet
624      40.0 Feet
625      40.0 Feet
626      45.0 Feet
627      60.0 Feet
628      40.0 Feet
629      40.0 Feet
630      40.0 Feet
631      40.0 Feet
632      40.0 Feet
633            NaN
634      40.0 Feet
635      40.0 Feet
636            NaN
637            NaN
638      40.0 Feet
639      40.0 Feet
640      40.0 Feet
641      40.0 Feet
642      40.0 Feet
643      40.0 Feet
644      40.0 Feet
645      40.0 Feet
646      40.0 Feet
647            NaN
648            NaN
649      50.0 Feet
650      50.0 Feet
651      50.0 Feet
652      50.0 Feet
653            NaN
654      55.0 Feet
655      50.0 Feet
656      50.0 Feet
657      60.0 Feet
658      50.0 Feet
659      50.0 Feet
660      50.0 Feet
661      40.0 Feet
662      50.0 Feet
663      50.0 Feet
664      45.0 Feet
665      45.0 Feet
666      50.0 Feet
667      50.0 Feet
668      50.0 Feet
669      50.0 Feet
670      55.0 Feet
671      55.0 Feet
672      45.0 Feet
673      40.0 Feet
674      45.0 Feet
675            NaN
676      50.0 Feet
677      50.0 Feet
678      40.0 Feet
679      40.0 Feet
680      40.0 Feet
681      40.0 Feet
682      40.0 Feet
683      40.0 Feet
684      40.0 Feet
685      40.0 Feet
686      45.0 Feet
687      40.0 Feet
688            NaN
689            NaN
690            NaN
691            NaN
692            NaN
693            NaN
694      40.0 Feet
695      60.0 Feet
696      40.0 Feet
697            NaN
698      40.0 Feet
699      40.0 Feet
700      40.0 Feet
701      40.0 Feet
702      40.0 Feet
703      40.0 Feet
704            NaN
705            NaN
706            NaN
707      40.0 Feet
708            NaN
709      40.0 Feet
710      40.0 Feet
711      40.0 Feet
712            NaN
713      40.0 Feet
714      40.0 Feet
715            NaN
716      40.0 Feet
717      40.0 Feet
718      40.0 Feet
719      40.0 Feet
720            NaN
721      40.0 Feet
722      40.0 Feet
723            NaN
724            NaN
725      40.0 Feet
726            NaN
727            NaN
728      40.0 Feet
729            NaN
730            NaN
731            NaN
732            NaN
733      40.0 Feet
734      40.0 Feet
735      40.0 Feet
736      40.0 Feet
737      40.0 Feet
738      40.0 Feet
739      40.0 Feet
740      40.0 Feet
741      40.0 Feet
742      40.0 Feet
743      40.0 Feet
744      80.0 Feet
745      40.0 Feet
746      40.0 Feet
747            NaN
748      40.0 Feet
749            NaN
750      40.0 Feet
751            NaN
752      40.0 Feet
753            NaN
754            NaN
755            NaN
756      40.0 Feet
757      30.0 Feet
758            NaN
759      40.0 Feet
760      40.0 Feet
761            NaN
762            NaN
763      45.0 Feet
764      55.0 Feet
765      40.0 Feet
766      50.0 Feet
767      45.0 Feet
768      50.0 Feet
769            NaN
770            NaN
771      40.0 Feet
772      50.0 Feet
773            NaN
774      45.0 Feet
775            NaN
776      50.0 Feet
777            NaN
778            NaN
779            NaN
780            NaN
781      50.0 Feet
782      50.0 Feet
783      45.0 Feet
784            NaN
785            NaN
786            NaN
787      50.0 Feet
788      50.0 Feet
789            NaN
790      50.0 Feet
791      60.0 Feet
792            NaN
793            NaN
794            NaN
795            NaN
796            NaN
797            NaN
798            NaN
799            NaN
800     112.0 Feet
801     115.0 Feet
802      50.0 Feet
803            NaN
804     112.0 Feet
805     112.0 Feet
806     111.0 Feet
807     118.0 Feet
808     112.0 Feet
809     112.0 Feet
810     125.0 Feet
811            NaN
812     113.0 Feet
813     111.0 Feet
814     111.0 Feet
815     126.0 Feet
816     112.0 Feet
817     115.0 Feet
818     112.0 Feet
819     111.0 Feet
820     116.0 Feet
821     112.0 Feet
822     111.0 Feet
823            NaN
824      45.0 Feet
825      50.0 Feet
826     115.0 Feet
827     111.0 Feet
828     110.0 Feet
829      52.0 Feet
830     112.0 Feet
831            NaN
832      50.0 Feet
833     118.0 Feet
834            NaN
835      50.0 Feet
836            NaN
837            NaN
838            NaN
839     110.0 Feet
840     112.0 Feet
841     110.0 Feet
842     120.0 Feet
843      45.0 Feet
844     117.0 Feet
845     112.0 Feet
846     112.0 Feet
847     110.0 Feet
848     142.0 Feet
849     112.0 Feet
850     112.0 Feet
851     115.0 Feet
852     100.0 Feet
853     109.0 Feet
854            NaN
855            NaN
856            NaN
857     118.0 Feet
858     115.0 Feet
859     115.0 Feet
860     112.0 Feet
861     492.1 Feet
862            NaN
863      40.0 Feet
864     115.0 Feet
865     111.0 Feet
866     111.0 Feet
867     111.0 Feet
868     115.0 Feet
869     112.0 Feet
870     116.0 Feet
871     117.0 Feet
872     112.0 Feet
873     112.0 Feet
874            NaN
875     115.0 Feet
876     117.0 Feet
877      60.0 Feet
878     100.0 Feet
879      60.0 Feet
880      45.0 Feet
881      60.0 Feet
882      50.0 Feet
883     112.0 Feet
884     121.0 Feet
885            NaN
886            NaN
887     115.0 Feet
888      55.8 Feet
889            NaN
890            NaN
891     112.0 Feet
892     112.0 Feet
893            NaN
894     112.0 Feet
895     112.0 Feet
896     112.0 Feet
897     112.0 Feet
898      40.0 Feet
899     114.0 Feet
900     145.0 Feet
901      48.0 Feet
902     114.0 Feet
903            NaN
904     114.0 Feet
905     119.0 Feet
906     115.0 Feet
907     114.0 Feet
908      50.0 Feet
909            NaN
910     112.0 Feet
911     128.0 Feet
912     111.0 Feet
913     112.0 Feet
914     112.0 Feet
915     127.0 Feet
916            NaN
917            NaN
918      50.0 Feet
919            NaN
920            NaN
921     126.0 Feet
922     152.0 Feet
923     116.0 Feet
924            NaN
925     112.0 Feet
926     112.0 Feet
927            NaN
928            NaN
929     115.0 Feet
930     115.0 Feet
931     112.0 Feet
932            NaN
933     112.0 Feet
934     100.0 Feet
935     112.0 Feet
936     112.0 Feet
937     112.0 Feet
938     112.0 Feet
939      45.0 Feet
940            NaN
941            NaN
942      52.0 Feet
943            NaN
944            NaN
945            NaN
946            NaN
947            NaN
948            NaN
949            NaN
950            NaN
951            NaN
952            NaN
953            NaN
954            NaN
955            NaN
956            NaN
957            NaN
958            NaN
959            NaN
960            NaN
961            NaN
962            NaN
963            NaN
964            NaN
965            NaN
966            NaN
967            NaN
968            NaN
969            NaN
970            NaN
971            NaN
972            NaN
973            NaN
974            NaN
975            NaN
976            NaN
977            NaN
978            NaN
979            NaN
980            NaN
981            NaN
982            NaN
983            NaN
984            NaN
985            NaN
986            NaN
987            NaN
988            NaN
989            NaN
990            NaN
991            NaN
992            NaN
993            NaN
994            NaN
995            NaN
996            NaN
997            NaN
998            NaN
999            NaN
1000           NaN
1001           NaN
1002           NaN
1003           NaN
1004           NaN
1005           NaN
1006           NaN
1007           NaN
1008           NaN
1009           NaN
1010           NaN
1011           NaN
1012           NaN
1013           NaN
1014           NaN
1015           NaN
1016           NaN
1017           NaN
1018           NaN
1019           NaN
1020           NaN
1021           NaN
1022           NaN
1023           NaN
1024           NaN
1025           NaN
1026           NaN
1027           NaN
1028           NaN
1029           NaN
1030           NaN
1031           NaN
1032           NaN
1033           NaN
1034           NaN
1035           NaN
1036           NaN
1037           NaN
1038           NaN
1039           NaN
1040           NaN
1041           NaN
1042           NaN
1043           NaN
1044           NaN
1045           NaN
1046           NaN
1047           NaN
1048           NaN
1049           NaN
1050           NaN
1051           NaN

In [161]:
df['RoadFacing'].isna().sum()

692

In [162]:
def road_fac_func(x):
    if pd.notna(x):
        return float(x.split(' ')[0])
    else:
        return x

In [163]:
df['RoadFacing'] = df['RoadFacing'].apply(road_fac_func)

In [164]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,Old,Marble,No,Semifurnished,40.0,"3 Covered, 3 Open","24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28 Cr
1,V75627519,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,Old,Others,No,Unfurnished,40.0,"1 Covered, 1 Open",Municipal corporation,NaN,Yes,No,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14 Cr
2,P75122867,6Bedrooms 6Baths,Independent House/Villa for Sale,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,RelNew,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,No,We have a house/villa available for sale in mo...,[],NaN,2.5 Cr
3,W75661879,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Club,Main Road,Others,Park/Garden,Pool,Sea facing",New,Others,Yes,Furnished,NaN,"1 Covered, 1 Open",24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.65 Cr
4,P75385469,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,UndConst,Ceramic,Yes,Semifurnished,30.0,"1 Covered, 1 Open",Borewell/Tank,NaN,NaN,No,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",58.9 Lac

### price

In [165]:
df['price']

0                      28 Cr
1                      14 Cr
2                     2.5 Cr
3                    1.65 Cr
4                   58.9 Lac
5                     4.5 Cr
6                      25 Cr
7                       4 Cr
8                     80 Lac
9                     80 Lac
10                    62 Lac
11                    65 Lac
12                      1 Cr
13                      8 Cr
14                    6.5 Cr
15                      7 Cr
16                      4 Cr
17                    80 Lac
18                    70 Lac
19                    4.1 Cr
20                    4.1 Cr
21                    1.5 Cr
22                   1.65 Cr
23                    1.5 Cr
24                  47.5 Lac
25                    70 Lac
26                   1.55 Cr
27                    76 Lac
28                    6.1 Cr
29                    4.5 Cr
30                    3.2 Cr
31                   4.75 Cr
32                   1.35 Cr
33                    1.5 Cr
34                    9.6 Cr
35                    45 Lac
36                    56 Lac
37                    3.5 Cr
38                    84 Lac
39                    2.2 Cr
40                    75 Lac
41                    98 Lac
42                    50 Lac
43                   1.75 Cr
44                    3.5 Cr
45                      1 Cr
46                     13 Cr
47                   14.5 Cr
48                   1.39 Cr
49                     32 Cr
50                     21 Cr
51                      4 Cr
52                   1.85 Cr
53                     24 Cr
54                    3.2 Cr
55                    2.9 Cr
56                   4.15 Cr
57                     14 Cr
58                   3.35 Cr
59                    60 Lac
60                      3 Cr
61                      4 Cr
62                    3.5 Cr
63                      2 Cr
64                    3.5 Cr
65                     28 Cr
66                   3.51 Cr
67                   2.21 Cr
68                   1.55 Cr
69                   1.95 Cr
70                   1.32 Cr
71                     17 Cr
72                      8 Cr
73                      6 Cr
74                   8.75 Cr
75                    7.5 Cr
76                     10 Cr
77                   17.5 Cr
78                    2.5 Cr
79                   13.5 Cr
80                   16.5 Cr
81                      8 Cr
82                     28 Cr
83                   8.25 Cr
84                   17.5 Cr
85                   8.35 Cr
86                     26 Cr
87                   7.25 Cr
88                    5.5 Cr
89                   6.75 Cr
90                     14 Cr
91                  11.25 Cr
92                   4.75 Cr
93                    4.1 Cr
94                      3 Cr
95                   13.5 Cr
96                   14.5 Cr
97                     65 Cr
98                     23 Cr
99                     25 Cr
100                   35 Lac
101                  1.43 Cr
102                  1.11 Cr
103                  1.35 Cr
104                    12 Cr
105                   1.3 Cr
106                   7.2 Cr
107                  1.34 Cr
108                  1.34 Cr
109                   3.7 Cr
110                  7.35 Cr
111                  3.45 Cr
112                  4.85 Cr
113                  5.95 Cr
114                   4.1 Cr
115                   7.6 Cr
116                  2.85 Cr
117                  2.95 Cr
118                   3.5 Cr
119                   5.5 Cr
120                   8.5 Cr
121                    60 Cr
122                     9 Cr
123                    27 Cr
124                    85 Cr
125                    35 Cr
126                    17 Cr
127                    17 Cr
128                    12 Cr
129                  11.5 Cr
130                  17.5 Cr
131                  16.5 Cr
132                    15 Cr
133                  15.5 Cr
134                    32 Cr
135                   7.5 Cr
136                  15.5 Cr
137                    65 Cr
138                  4.25 Cr
139                  4.25 Cr
140                  16.5 Cr
141                  9.25 Cr
142                   85 Lac
143                  8.25 Cr
144                  1.15 Cr
145                  3.25 Cr
146                   1.4 Cr
147                     6 Cr
148                   2.6 Cr
149                   80 Lac
150                  1.95 Cr
151                     3 Cr
152                   3.5 Cr
153                   4.5 Cr
154                   3.3 Cr
155                  1.32 Cr
156                  1.25 Cr
157                  3.25 Cr
158                   4.5 Cr
159                 13.25 Cr
160                   4.5 Cr
161                   4.5 Cr
162                  25.5 Cr
163                    14 Cr
164                 13.75 Cr
165                    14 Cr
166                    72 Cr
167                    32 Cr
168                 17.75 Cr
169                  5.75 Cr
170                    10 Cr
171                   2.1 Cr
172                   1.6 Cr
173                    28 Cr
174                   3.3 Cr
175                  1.35 Cr
176                   3.6 Cr
177                   4.4 Cr
178                  4.95 Cr
179                  2.07 Cr
180                   85 Lac
181                   2.6 Cr
182                  1.75 Cr
183                    45 Cr
184                  16.5 Cr
185                    45 Cr
186                    47 Cr
187                    40 Cr
188                    32 Cr
189                    52 Cr
190                    55 Cr
191                    26 Cr
192                    50 Cr
193                    18 Cr
194                    35 Cr
195                    20 Cr
196                    60 Cr
197                    30 Cr
198                    22 Cr
199                    21 Cr
200                    85 Cr
201                    17 Cr
202                    85 Cr
203                    70 Cr
204                    12 Cr
205                   2.9 Cr
206                  5.47 Cr
207                   1.3 Cr
208                   1.5 Cr
209                  1.32 Cr
210                    29 Cr
211                   6.8 Cr
212                    80 Cr
213                    38 Cr
214                  31.5 Cr
215                  54.5 Cr
216                  14.5 Cr
217                  16.5 Cr
218                  15.5 Cr
219                    14 Cr
220                    14 Cr
221                    26 Cr
222                  19.5 Cr
223                    26 Cr
224                   5.5 Cr
225                    14 Cr
226                  3.55 Cr
227                  12.5 Cr
228                 14.25 Cr
229                  12.5 Cr
230                     7 Cr
231                  11.5 Cr
232                  11.5 Cr
233                    13 Cr
234                  28.5 Cr
235                  15.5 Cr
236                  27.5 Cr
237                    32 Cr
238                  12.5 Cr
239                    24 Cr
240                  16.5 Cr
241                    13 Cr
242                  16.5 Cr
243                   2.6 Cr
244                  16.5 Cr
245                   8.5 Cr
246                     3 Cr
247                   6.8 Cr
248                   8.5 Cr
249                   6.5 Cr
250                   7.6 Cr
251                    16 Cr
252                   5.8 Cr
253                     6 Cr
254                  7.25 Cr
255                  6.25 Cr
256                   5.4 Cr
257                   3.6 Cr
258                   8.5 Cr
259                     8 Cr
260                   1.9 Cr
261                   1.4 Cr
262                  1.95 Cr
263                   1.3 Cr
264                  3.25 Cr
265                    25 Cr
266                   8.5 Cr
267                   6.9 Cr
268                    16 Cr
269                   3.5 Cr
270                   5.4 Cr
271                    22 Cr
272                   7.5 Cr
273                  13.5 Cr
274                   4.5 Cr
275                    20 Cr
276                    20 Cr
277                  3.25 Cr
278                   3.5 Cr
279                    27 Cr
280                    25 Cr
281                     5 Cr
282                  14.5 Cr
283                     7 Cr
284                   3.2 Cr
285                   7.1 Cr
286                   4.2 Cr
287                  4.25 Cr
288                    15 Cr
289                   6.5 Cr
290                   6.5 Cr
291                     8 Cr
292                     8 Cr
293                   6.5 Cr
294                   5.6 Cr
295                   5.5 Cr
296                  4.75 Cr
297                  14.5 Cr
298                  7.25 Cr
299                     8 Cr
300                  6.25 Cr
301                   70 Lac
302                   8.5 Cr
303                  6.25 Cr
304                  4.75 Cr
305                  6.75 Cr
306                     7 Cr
307                  15.5 Cr
308                    17 Cr
309                  13.7 Cr
310                   6.8 Cr
311                   8.1 Cr
312                    27 Cr
313                    17 Cr
314                 14.25 Cr
315                   3.7 Cr
316                     7 Cr
317                     7 Cr
318                    35 Cr
319                  16.5 Cr
320                  13.5 Cr
321                 14.25 Cr
322                 11.85 Cr
323                    12 Cr
324                   4.8 Cr
325                   4.4 Cr
326                  16.5 Cr
327                  14.5 Cr
328                  7.25 Cr
329                     4 Cr
330                  5.75 Cr
331                    12 Cr
332                     5 Cr
333                   5.6 Cr
334                   8.1 Cr
335                  4.15 Cr
336                  7.25 Cr
337                   8.5 Cr
338                   5.1 Cr
339                   3.1 Cr
340                 11.15 Cr
341                 11.25 Cr
342                   4.5 Cr
343                    30 Cr
344                  6.75 Cr
345                   7.5 Cr
346                   8.5 Cr
347                   5.5 Cr
348                     6 Cr
349                  2.35 Cr
350                     4 Cr
351                  1.35 Cr
352                  7.25 Cr
353                    36 Cr
354                  15.5 Cr
355                  6.21 Cr
356                  14.5 Cr
357                  14.5 Cr
358                  7.21 Cr
359                     7 Cr
360                  6.21 Cr
361                   3.5 Cr
362                   5.5 Cr
363                  11.5 Cr
364                  6.55 Cr
365                   2.7 Cr
366                   3.6 Cr
367                   5.5 Cr
368                     4 Cr
369                  6.75 Cr
370                  13.5 Cr
371                  2.65 Cr
372                  14.5 Cr
373                    32 Cr
374                    14 Cr
375                   7.5 Cr
376                    24 Cr
377                  7.75 Cr
378                     9 Cr
379                 13.25 Cr
380                  4.75 Cr
381                   4.1 Cr
382                  13.5 Cr
383                  8.95 Cr
384                   4.1 Cr
385                   8.5 Cr
386                     5 Cr
387                  11.5 Cr
388                  14.5 Cr
389                  12.5 Cr
390                   4.6 Cr
391                   4.5 Cr
392                  2.75 Cr
393                  3.95 Cr
394                   3.3 Cr
395                   7.5 Cr
396                  6.25 Cr
397                   4.7 Cr
398                  13.5 Cr
399                   6.5 Cr
400                  1.15 Cr
401                 13.25 Cr
402                 62.5 Lac
403                  1.15 Cr
404                  4.25 Cr
405                   6.4 Cr
406                   6.2 Cr
407                     6 Cr
408                    15 Cr
409                    17 Cr
410                    15 Cr
411                    16 Cr
412                     8 Cr
413                    80 Cr
414                   7.5 Cr
415                   7.9 Cr
416                  12.5 Cr
417                    12 Cr
418                  11.5 Cr
419                    11 Cr
420                  10.5 Cr
421                    10 Cr
422                  2.75 Cr
423                   2.5 Cr
424                  2.25 Cr
425                     2 Cr
426                     4 Cr
427                  4.25 Cr
428                   6.8 Cr
429                   7.2 Cr
430                     7 Cr
431                     6 Cr
432                   6.2 Cr
433                   5.8 Cr
434                   4.2 Cr
435                     4 Cr
436                   3.8 Cr
437                     5 Cr
438                   3.9 Cr
439                   3.9 Cr
440                  3.75 Cr
441                    25 Cr
442                   2.6 Cr
443                  2.06 Cr
444                   7.5 Cr
445                  3.94 Cr
446                   1.7 Cr
447                   2.6 Cr
448                  6.25 Cr
449                   5.1 Cr
450                  3.65 Cr
451                  6.25 Cr
452                   2.9 Cr
453                  4.75 Cr
454                   2.6 Cr
455                     6 Cr
456                     4 Cr
457                   4.5 Cr
458                    21 Cr
459                   1.6 Cr
460                     6 Cr
461                  8.25 Cr
462                   7.5 Cr
463                   6.8 Cr
464                  6.75 Cr
465                   6.5 Cr
466                     8 Cr
467                  4.65 Cr
468                  13.5 Cr
469                    16 Cr
470                    14 Cr
471                  13.5 Cr
472                     5 Cr
473                 13.75 Cr
474                 11.85 Cr
475                   5.5 Cr
476                     5 Cr
477                   4.5 Cr
478                  4.25 Cr
479                     3 Cr
480                  2.85 Cr
481                   2.6 Cr
482                  6.75 Cr
483                   5.5 Cr
484                  6.25 Cr
485                   7.5 Cr
486                     5 Cr
487                   6.5 Cr
488                  5.25 Cr
489                     6 Cr
490                   6.5 Cr
491                    17 Cr
492                  6.65 Cr
493                   7.5 Cr
494                     7 Cr
495                     7 Cr
496                   5.5 Cr
497                   7.5 Cr
498                     7 Cr
499                     7 Cr
500                   7.5 Cr
501                  5.25 Cr
502                   7.5 Cr
503                   5.5 Cr
504                  6.65 Cr
505                   5.5 Cr
506                     5 Cr
507                  6.25 Cr
508                   5.5 Cr
509                   4.5 Cr
510                   7.5 Cr
511                   5.5 Cr
512                   5.5 Cr
513                    14 Cr
514                    17 Cr
515                 13.25 Cr
516                    13 Cr
517                 15.05 Cr
518                    14 Cr
519                  14.5 Cr
520                    25 Cr
521                    28 Cr
522                    27 Cr
523                  10.5 Cr
524                  10.5 Cr
525                  13.5 Cr
526                    11 Cr
527                  11.5 Cr
528                   3.6 Cr
529                  12.5 Cr
530                    13 Cr
531                  4.25 Cr
532                     4 Cr
533                   4.5 Cr
534                    15 Cr
535                    13 Cr
536                  12.5 Cr
537                    13 Cr
538                  13.5 Cr
539                    13 Cr
540                   6.5 Cr
541                   4.1 Cr
542                     4 Cr
543                  4.25 Cr
544                   4.5 Cr
545                   4.5 Cr
546                  1.05 Cr
547                   95 Lac
548                  1.45 Cr
549                  1.46 Cr
550                     3 Cr
551                  3.25 Cr
552                  6.25 Cr
553                     8 Cr
554                   3.6 Cr
555                  3.25 Cr
556                  8.25 Cr
557                   6.1 Cr
558                  4.25 Cr
559                  4.75 Cr
560                  3.75 Cr
561                     8 Cr
562                   3.5 Cr
563                   4.7 Cr
564                  7.75 Cr
565                   3.1 Cr
566                    29 Cr
567                   4.5 Cr
568                    13 Cr
569                   1.5 Cr
570                  1.45 Cr
571                  1.35 Cr
572                   1.5 Cr
573                  1.55 Cr
574                   1.6 Cr
575                  7.75 Cr
576                  7.75 Cr
577                    18 Cr
578                  12.5 Cr
579                  8.25 Cr
580                  1.55 Cr
581                  1.72 Cr
582                  6.25 Cr
583                   2.4 Cr
584                  14.5 Cr
585                   1.2 Cr
586                  6.25 Cr
587                   7.5 Cr
588                   7.5 Cr
589                  6.25 Cr
590                     3 Cr
591                     8 Cr
592                  13.5 Cr
593                  14.5 Cr
594                  6.25 Cr
595                  5.75 Cr
596                  6.75 Cr
597                   2.8 Cr
598                 13.75 Cr
599                    12 Cr
600                  13.5 Cr
601                   6.1 Cr
602                   6.5 Cr
603                  2.75 Cr
604                   7.6 Cr
605                     8 Cr
606                  6.25 Cr
607                    27 Cr
608                  5.25 Cr
609                     3 Cr
610                   6.5 Cr
611                    60 Cr
612                    14 Cr
613                    80 Cr
614                    14 Cr
615                  3.75 Cr
616                     5 Cr
617                     7 Cr
618                     8 Cr
619                   4.1 Cr
620                  5.25 Cr
621                  6.25 Cr
622                   5.1 Cr
623                  4.75 Cr
624                   7.5 Cr
625                   4.5 Cr
626                  13.5 Cr
627                  5.75 Cr
628                  7.75 Cr
629                     4 Cr
630                    23 Cr
631                   5.5 Cr
632                    15 Cr
633                    24 Cr
634                   2.7 Cr
635                  11.5 Cr
636                    21 Cr
637                   2.9 Cr
638                   3.5 Cr
639                  6.25 Cr
640                   6.5 Cr
641                  6.25 Cr
642                  5.75 Cr
643                  7.25 Cr
644                     8 Cr
645                   8.5 Cr
646                  6.75 Cr
647                  4.15 Cr
648                    60 Cr
649                    45 Cr
650                    40 Cr
651                    38 Cr
652                  11.5 Cr
653                   4.6 Cr
654     Available on Request
655                   4.9 Cr
656                  4.75 Cr
657                  4.65 Cr
658                     9 Cr
659                    21 Cr
660                    11 Cr
661                   6.4 Cr
662                  11.4 Cr
663                   5.1 Cr
664                 12.75 Cr
665                  10.5 Cr
666                    11 Cr
667                 18.75 Cr
668                 12.25 Cr
669                 12.75 Cr
670                  11.5 Cr
671                  10.5 Cr
672                  10.9 Cr
673                 11.25 Cr
674                 11.25 Cr
675                  11.2 Cr
676                     5 Cr
677                    12 Cr
678                   6.5 Cr
679                   6.9 Cr
680                  6.75 Cr
681                   6.5 Cr
682                  7.25 Cr
683                    12 Cr
684                  11.5 Cr
685                     9 Cr
686                  6.75 Cr
687                     7 Cr
688                  5.75 Cr

In [166]:
df[df['price'] == 'Price on Request']

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
1106,M68946714,1Bedroom 1Bath,Independent House/Villa for Sale,https://www.99acres.com/1-bhk-bedroom-independ...,NaN,"Sector 28 Chandigarh, Chandigarh, India","Sector 28, Sector 28 Chandigarh, Chandigarh, I...",NaN,Built Up area: 250 (23.23 sq.m.) sq.ft.,sq.ft.,1,1,1,NaN,East,2,NaN,UndConst,NaN,No,Furnished,NaN,NaN,NaN,NaN,NaN,No,3 storeyed house is a great property to invest...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,Price on Request

In [167]:
df[df['price'] == 'Available on Request']

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,RoadFacing,Parking,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
654,I56146730,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 33 Chandigarh, Chandigarh, India","Sector 33 Chandigarh, Chandigarh, India","10,25,00,000 per kanal",Plot area 1(505.86 sq.m.) kanal,kanal,7,7,3,"Pooja Room,Study Room,Servant Room,Others",North-East,3,Main Road,Old,Mosaic,Yes,Unfurnished,55.0,"3 Covered, 2 Open","Borewell/Tank,Municipal corporation",Partial,Yes,Yes,Old liveable triple story corner 1 kanal house...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...",Available on Request

In [168]:
df.drop([1106,654],inplace = True)

In [169]:
def price_func(x):
    if pd.notna(x):
        temp = x.split(' ')
        if temp[-1] == 'Cr':
            return float(temp[0])
        elif temp[-1] == 'Lac':
            return (float(temp[0]))/100
        else:
            return x
    else:
        return x

In [172]:
df['price']

0       28.000
1       14.000
2        2.500
3        1.650
4        0.589
5        4.500
6       25.000
7        4.000
8        0.800
9        0.800
10       0.620
11       0.650
12       1.000
13       8.000
14       6.500
15       7.000
16       4.000
17       0.800
18       0.700
19       4.100
20       4.100
21       1.500
22       1.650
23       1.500
24       0.475
25       0.700
26       1.550
27       0.760
28       6.100
29       4.500
30       3.200
31       4.750
32       1.350
33       1.500
34       9.600
35       0.450
36       0.560
37       3.500
38       0.840
39       2.200
40       0.750
41       0.980
42       0.500
43       1.750
44       3.500
45       1.000
46      13.000
47      14.500
48       1.390
49      32.000
50      21.000
51       4.000
52       1.850
53      24.000
54       3.200
55       2.900
56       4.150
57      14.000
58       3.350
59       0.600
60       3.000
61       4.000
62       3.500
63       2.000
64       3.500
65      28.000
66       3.510
67       2.210
68       1.550
69       1.950
70       1.320
71      17.000
72       8.000
73       6.000
74       8.750
75       7.500
76      10.000
77      17.500
78       2.500
79      13.500
80      16.500
81       8.000
82      28.000
83       8.250
84      17.500
85       8.350
86      26.000
87       7.250
88       5.500
89       6.750
90      14.000
91      11.250
92       4.750
93       4.100
94       3.000
95      13.500
96      14.500
97      65.000
98      23.000
99      25.000
100      0.350
101      1.430
102      1.110
103      1.350
104     12.000
105      1.300
106      7.200
107      1.340
108      1.340
109      3.700
110      7.350
111      3.450
112      4.850
113      5.950
114      4.100
115      7.600
116      2.850
117      2.950
118      3.500
119      5.500
120      8.500
121     60.000
122      9.000
123     27.000
124     85.000
125     35.000
126     17.000
127     17.000
128     12.000
129     11.500
130     17.500
131     16.500
132     15.000
133     15.500
134     32.000
135      7.500
136     15.500
137     65.000
138      4.250
139      4.250
140     16.500
141      9.250
142      0.850
143      8.250
144      1.150
145      3.250
146      1.400
147      6.000
148      2.600
149      0.800
150      1.950
151      3.000
152      3.500
153      4.500
154      3.300
155      1.320
156      1.250
157      3.250
158      4.500
159     13.250
160      4.500
161      4.500
162     25.500
163     14.000
164     13.750
165     14.000
166     72.000
167     32.000
168     17.750
169      5.750
170     10.000
171      2.100
172      1.600
173     28.000
174      3.300
175      1.350
176      3.600
177      4.400
178      4.950
179      2.070
180      0.850
181      2.600
182      1.750
183     45.000
184     16.500
185     45.000
186     47.000
187     40.000
188     32.000
189     52.000
190     55.000
191     26.000
192     50.000
193     18.000
194     35.000
195     20.000
196     60.000
197     30.000
198     22.000
199     21.000
200     85.000
201     17.000
202     85.000
203     70.000
204     12.000
205      2.900
206      5.470
207      1.300
208      1.500
209      1.320
210     29.000
211      6.800
212     80.000
213     38.000
214     31.500
215     54.500
216     14.500
217     16.500
218     15.500
219     14.000
220     14.000
221     26.000
222     19.500
223     26.000
224      5.500
225     14.000
226      3.550
227     12.500
228     14.250
229     12.500
230      7.000
231     11.500
232     11.500
233     13.000
234     28.500
235     15.500
236     27.500
237     32.000
238     12.500
239     24.000
240     16.500
241     13.000
242     16.500
243      2.600
244     16.500
245      8.500
246      3.000
247      6.800
248      8.500
249      6.500
250      7.600
251     16.000
252      5.800
253      6.000
254      7.250
255      6.250
256      5.400
257      3.600
258      8.500
259      8.000
260      1.900
261      1.400
262      1.950
263      1.300
264      3.250
265     25.000
266      8.500
267      6.900
268     16.000
269      3.500
270      5.400
271     22.000
272      7.500
273     13.500
274      4.500
275     20.000
276     20.000
277      3.250
278      3.500
279     27.000
280     25.000
281      5.000
282     14.500
283      7.000
284      3.200
285      7.100
286      4.200
287      4.250
288     15.000
289      6.500
290      6.500
291      8.000
292      8.000
293      6.500
294      5.600
295      5.500
296      4.750
297     14.500
298      7.250
299      8.000
300      6.250
301      0.700
302      8.500
303      6.250
304      4.750
305      6.750
306      7.000
307     15.500
308     17.000
309     13.700
310      6.800
311      8.100
312     27.000
313     17.000
314     14.250
315      3.700
316      7.000
317      7.000
318     35.000
319     16.500
320     13.500
321     14.250
322     11.850
323     12.000
324      4.800
325      4.400
326     16.500
327     14.500
328      7.250
329      4.000
330      5.750
331     12.000
332      5.000
333      5.600
334      8.100
335      4.150
336      7.250
337      8.500
338      5.100
339      3.100
340     11.150
341     11.250
342      4.500
343     30.000
344      6.750
345      7.500
346      8.500
347      5.500
348      6.000
349      2.350
350      4.000
351      1.350
352      7.250
353     36.000
354     15.500
355      6.210
356     14.500
357     14.500
358      7.210
359      7.000
360      6.210
361      3.500
362      5.500
363     11.500
364      6.550
365      2.700
366      3.600
367      5.500
368      4.000
369      6.750
370     13.500
371      2.650
372     14.500
373     32.000
374     14.000
375      7.500
376     24.000
377      7.750
378      9.000
379     13.250
380      4.750
381      4.100
382     13.500
383      8.950
384      4.100
385      8.500
386      5.000
387     11.500
388     14.500
389     12.500
390      4.600
391      4.500
392      2.750
393      3.950
394      3.300
395      7.500
396      6.250
397      4.700
398     13.500
399      6.500
400      1.150
401     13.250
402      0.625
403      1.150
404      4.250
405      6.400
406      6.200
407      6.000
408     15.000
409     17.000
410     15.000
411     16.000
412      8.000
413     80.000
414      7.500
415      7.900
416     12.500
417     12.000
418     11.500
419     11.000
420     10.500
421     10.000
422      2.750
423      2.500
424      2.250
425      2.000
426      4.000
427      4.250
428      6.800
429      7.200
430      7.000
431      6.000
432      6.200
433      5.800
434      4.200
435      4.000
436      3.800
437      5.000
438      3.900
439      3.900
440      3.750
441     25.000
442      2.600
443      2.060
444      7.500
445      3.940
446      1.700
447      2.600
448      6.250
449      5.100
450      3.650
451      6.250
452      2.900
453      4.750
454      2.600
455      6.000
456      4.000
457      4.500
458     21.000
459      1.600
460      6.000
461      8.250
462      7.500
463      6.800
464      6.750
465      6.500
466      8.000
467      4.650
468     13.500
469     16.000
470     14.000
471     13.500
472      5.000
473     13.750
474     11.850
475      5.500
476      5.000
477      4.500
478      4.250
479      3.000
480      2.850
481      2.600
482      6.750
483      5.500
484      6.250
485      7.500
486      5.000
487      6.500
488      5.250
489      6.000
490      6.500
491     17.000
492      6.650
493      7.500
494      7.000
495      7.000
496      5.500
497      7.500
498      7.000
499      7.000
500      7.500
501      5.250
502      7.500
503      5.500
504      6.650
505      5.500
506      5.000
507      6.250
508      5.500
509      4.500
510      7.500
511      5.500
512      5.500
513     14.000
514     17.000
515     13.250
516     13.000
517     15.050
518     14.000
519     14.500
520     25.000
521     28.000
522     27.000
523     10.500
524     10.500
525     13.500
526     11.000
527     11.500
528      3.600
529     12.500
530     13.000
531      4.250
532      4.000
533      4.500
534     15.000
535     13.000
536     12.500
537     13.000
538     13.500
539     13.000
540      6.500
541      4.100
542      4.000
543      4.250
544      4.500
545      4.500
546      1.050
547      0.950
548      1.450
549      1.460
550      3.000
551      3.250
552      6.250
553      8.000
554      3.600
555      3.250
556      8.250
557      6.100
558      4.250
559      4.750
560      3.750
561      8.000
562      3.500
563      4.700
564      7.750
565      3.100
566     29.000
567      4.500
568     13.000
569      1.500
570      1.450
571      1.350
572      1.500
573      1.550
574      1.600
575      7.750
576      7.750
577     18.000
578     12.500
579      8.250
580      1.550
581      1.720
582      6.250
583      2.400
584     14.500
585      1.200
586      6.250
587      7.500
588      7.500
589      6.250
590      3.000
591      8.000
592     13.500
593     14.500
594      6.250
595      5.750
596      6.750
597      2.800
598     13.750
599     12.000
600     13.500
601      6.100
602      6.500
603      2.750
604      7.600
605      8.000
606      6.250
607     27.000
608      5.250
609      3.000
610      6.500
611     60.000
612     14.000
613     80.000
614     14.000
615      3.750
616      5.000
617      7.000
618      8.000
619      4.100
620      5.250
621      6.250
622      5.100
623      4.750
624      7.500
625      4.500
626     13.500
627      5.750
628      7.750
629      4.000
630     23.000
631      5.500
632     15.000
633     24.000
634      2.700
635     11.500
636     21.000
637      2.900
638      3.500
639      6.250
640      6.500
641      6.250
642      5.750
643      7.250
644      8.000
645      8.500
646      6.750
647      4.150
648     60.000
649     45.000
650     40.000
651     38.000
652     11.500
653      4.600
655      4.900
656      4.750
657      4.650
658      9.000
659     21.000
660     11.000
661      6.400
662     11.400
663      5.100
664     12.750
665     10.500
666     11.000
667     18.750
668     12.250
669     12.750
670     11.500
671     10.500
672     10.900
673     11.250
674     11.250
675     11.200
676      5.000
677     12.000
678      6.500
679      6.900
680      6.750
681      6.500
682      7.250
683     12.000
684     11.500
685      9.000
686      6.750
687      7.000
688      5.750
689      5.250
690      7.500
691      4.000
692      5.000
693     23.000
694     24.000
695     13.000
696      2.400
697     12.000
698      3.500
699      5.500
700     13.000
701      4.000
702     13.000
703     22.000
704     13.000
705      3.500
706      3.750
707     22.000
708      2.600
709      5.500
710     21.000
711      7.250
712      2.400
713      4.000
714      4.000
715      3.750
716     25.000
717      5.500
718      6.100
719      2.600
720     14.000
721     25.000
722     14.000
723     11.000
724     13.500
725      7.750
726      3.350
727     13.500
728     22.000
729      5.500
730      5.500
731      4.250
732     14.000
733      2.750
734      5.100
735      3.500
736      6.000
737      5.250
738      8.250
739      5.200
740      3.900
741      4.800
742     11.500
743      4.000
744      7.000
745     13.000
746      4.450
747      4.500
748      7.500
749      2.750
750      7.250
751      4.600
752      7.500
753      3.800
754      4.900
755      3.800
756      3.250
757      2.500
758      5.500
759     54.000
760     28.000
761      4.750
762     16.500
763     11.650
764     13.000
765     22.750
766     11.850
767     23.250
768     23.800
769     13.650
770      2.550
771      4.650
772     12.650
773      5.580
774     12.950
775      4.150
776     23.500
777      5.250
778     24.500
779      3.980
780     14.100
781     11.150
782     23.250
783     12.950
784      3.900
785      4.980
786      5.400
787      5.450
788     10.650
789      4.800
790     13.150
791      3.780
792     13.720
793     14.450
794     13.250
795     12.250
796      5.350
797     14.170
798     11.400
799     13.980
800      4.190
801      2.620
802      5.100
803      2.550
804      8.150
805      2.800
806      5.250
807     24.000
808     11.750
809      5.430
810     22.550
811      5.850
812      4.850
813      4.890
814      3.820
815      5.650
816      5.280
817      5.180
818      5.450
819      4.120
820     13.100
821      5.380
822      3.050
823      3.700
824     13.150
825     24.750
826      5.150
827      5.780
828      5.850
829     13.580
830      4.150
831     13.350
832      4.920
833      4.180
834      5.420
835      3.350
836      3.150
837      5.420
838     24.500
839      5.920
840      5.450
841     69.000
842     24.520
843     55.000
844     14.350
845      5.950
846      4.150
847     64.500
848      7.950
849      8.120
850     20.250
851      6.580
852      7.250
853      5.850
854      5.420
855      2.420
856     11.550
857      6.120
858      2.550
859      2.450
860     12.350
861      5.850
862      2.470
863      4.120
864      3.650
865      3.200
866      3.280
867      3.100
868      4.620
869     13.100
870     13.250
871      5.500
872      5.250
873      3.730
874     62.000
875      3.820
876      5.420
877     13.600
878      5.820
879     14.180
880     27.520
881     26.420
882     14.150
883     12.250
884      3.750
885      3.780
886      2.240
887     14.150
888      4.370
889      2.900
890      5.150
891     57.000
892     14.120
893      5.480
894     59.000
895     51.000
896     57.000
897      3.780
898     10.500
899      4.500
900      3.750
901     25.600
902      3.720
903     14.150
904      4.720
905      5.000
906      5.180
907      4.920
908      3.480
909      3.650
910      6.500
911      2.480
912      4.720
913      3.920
914      3.810
915      2.550
916      2.580
917     11.800
918     13.550
919     20.250
920      5.050
921     13.850
922     13.700
923      5.380
924      5.280
925     10.300
926      5.250
927     10.250
928      5.550
929     13.650
930      5.450
931      5.380
932     12.850
933     13.780
934      2.300
935     12.900
936     13.750
937     26.500
938      3.750
939     14.150
940     15.250
941     63.000
942      2.650
943     13.750
944     13.950
945      8.300
946      8.250
947     16.500
948      4.200
949     12.500
950      6.000
951      7.750
952      4.150
953     33.000
954      4.250
955      5.450
956     15.250
957      7.500
958      7.450
959      6.000
960     14.500
961     14.500
962      5.700
963     17.000
964      4.600
965      6.750
966      6.750
967      4.200
968      7.000
969     15.000
970      9.250
971      7.350
972      6.000
973      8.250
974      6.850
975     25.000
976      6.500
977     13.500
978      7.350
979     16.750
980      6.550
981      7.200
982      6.250
983      6.200
984     26.000
985     14.000
986     15.000
987      6.700
988      4.600
989     16.000
990      6.250
991      5.500
992      4.150
993     15.000
994      7.000
995     16.000
996     14.500
997     16.000
998     34.000
999     14.000
1000    14.000
1001    33.000
1002    33.000
1003    30.000
1004    15.000
1005    15.000
1006    32.000
1007    22.000
1008    22.000
1009    16.000
1010    16.500
1011    16.500
1012     8.250
1013    16.500
1014    32.000
1015     6.250
1016     4.000
1017     5.500
1018     8.500
1019     6.300
1020     7.500
1021     4.150
1022     4.500
1023    20.000
1024    15.550
1025    20.000
1026     3.700
1027     4.200
1028     9.000
1029     8.250
1030     7.000
1031    22.000
1032     6.500
1033     8.150
1034     6.000
1035     8.500
1036     6.850
1037     3.600
1038     8.750
1039     5.800
1040     6.250
1041     4.750
1042    14.000
1043     6.100
1044    19.500
1045    14.200
1046     7.300
1047     4.250
1048     8.500
1049     4.200
1050     9.600
1051     6.500
1052     5.500
1053     5.500
1054     5.500
1055     4.000
1056     4.250
1057     6.730
1058     7.750
1059     7.750
1060     5.200
1061     6.000
1062     5.700
1063    16.500
1064    15.500
1065     5.000
1066     1.600
1067     5.470
1068     5.200
1069    16.500
1070     1.350
1071     0.310
1072     7.000
1073     4.250
1074     8.100
1075     1.350
1076     1.550
1077     1.000
1078     5.650
1079     6.500
1080     6.500
1081     1.350
1082     2.500
1083     5.500
1084     7.750
1085    16.500
1086     1.340
1087    24.000
1088    13.500
1089     0.700
1090     3.000
1091    17.000
1092     7.500
1093    44.000
1094     6.000
1095     0.450
1096     0.400
1097     0.800
1098     0.650
1099     0.950
1100     7.500
1101    12.500
1102     3.500
1103     0.350
1104     0.400
1105     2.850
1107     0.520
1108     1.750
1109     0.200
1110     0.720
1111     6.500
1112     0.450
1113     1.600
1114     0.700
1115     3.700
1116     4.350
1117    17.160
1118    28.000
1119     0.380
1120     0.319
1121     5.600
1122     6.100
1123     0.800
1124     2.400
1125     3.600
1126     3.690
1127     0.275
1128     7.750
1129     0.380
1130     0.480
1131    16.000
1132    13.000
1133     3.100
1134     0.500
1135     0.480
1136     0.389
1137     1.200
1138     0.280
1139     1.000
1140     0.750
1141     1.100
1142     6.790
1143     0.660
1144     2.800
1145     6.500
1146     0.340
1147     5.400
1148     4.500
1149     0.730
1150     4.000
1151     6.150
1152     7.000
1153     0.450
1154     0.900
1155     4.000
1156     0.420
1157     1.850
1158     0.350
1159     0.399
1160     4.000
1161     0.470
1162     4.000
1163     0.280
1164     3.700
1165    27.000
1166     0.490
1167     0.580
1168     1.350
1169     0.320
1170     2.300
1171     0.450
1172     0.650
1173     1.500
1174     0.850
1175     0.550
1176     0.780
1177     2.000
1178     0.540
1179     0.750
1180     3.150
1181     4.750
1182     1.500
1183     1.250
1184     0.450
1185     0.170
1186     1.250
1187     0.720
1188     0.370
1189     0.300
1190     0.260
1191     0.500
1192     5.500
1193     0.385
1194     0.300
1195     0.525
1196     3.000
1197     0.350
1198     1.000
1199     6.750
1200     0.490
1201     4.000
1202     1.100
1203     0.550
1204     0.850
1205     0.750
1206     1.450
1207     0.600
Name: price, dtype: float64

In [171]:
df['price'] = df['price'].apply(price_func)

### Parking

In [173]:
df['Parking']

0        3 Covered, 3 Open
1        1 Covered, 1 Open
2                      NaN
3        1 Covered, 1 Open
4        1 Covered, 1 Open
5        2 Covered, 1 Open
6        2 Covered, 2 Open
7                   2 Open
8                      NaN
9                      NaN
10       1 Covered, 1 Open
11                  1 Open
12                     NaN
13                     NaN
14                  4 Open
15       1 Covered, 2 Open
16       1 Covered, 1 Open
17               1 Covered
18         Covered, 0 Open
19         Covered, 2 Open
20          Covered,  Open
21       1 Covered, 1 Open
22                  1 Open
23               1 Covered
24                  1 Open
25                     NaN
26       2 Covered, 1 Open
27       1 Covered, 1 Open
28       1 Covered, 3 Open
29                     NaN
30                  2 Open
31                  6 Open
32                     NaN
33                     NaN
34       1 Covered, 1 Open
35                  1 Open
36                  1 Open
37       2 Covered, 4 Open
38                  1 Open
39       0 Covered, 0 Open
40        1 Covered,  Open
41                     NaN
42       1 Covered, 2 Open
43                     NaN
44       1 Covered, 2 Open
45       1 Covered, 0 Open
46       2 Covered, 2 Open
47       2 Covered, 2 Open
48                  3 Open
49       2 Covered, 2 Open
50       2 Covered, 1 Open
51       2 Covered, 2 Open
52       2 Covered, 1 Open
53       4 Covered, 3 Open
54       2 Covered, 2 Open
55       1 Covered, 2 Open
56       2 Covered, 2 Open
57       2 Covered, 4 Open
58       2 Covered, 4 Open
59       1 Covered, 1 Open
60       1 Covered, 2 Open
61                     NaN
62       1 Covered, 2 Open
63       1 Covered, 1 Open
64       2 Covered, 1 Open
65       3 Covered, 3 Open
66                  3 Open
67       2 Covered, 3 Open
68       1 Covered, 1 Open
69       1 Covered, 1 Open
70                  2 Open
71       2 Covered, 4 Open
72      2 Covered, 10 Open
73       1 Covered, 3 Open
74       2 Covered, 4 Open
75       2 Covered, 4 Open
76       2 Covered, 2 Open
77       3 Covered, 2 Open
78       2 Covered, 2 Open
79       2 Covered, 2 Open
80       3 Covered, 2 Open
81       2 Covered, 6 Open
82       4 Covered, 6 Open
83       3 Covered, 3 Open
84       2 Covered, 4 Open
85       2 Covered, 4 Open
86                     NaN
87                  4 Open
88                  2 Open
89       1 Covered, 2 Open
90       1 Covered, 3 Open
91                  3 Open
92                  3 Open
93                  2 Open
94                  2 Open
95       1 Covered, 3 Open
96       1 Covered, 3 Open
97       6 Covered, 7 Open
98                  6 Open
99       4 Covered, 4 Open
100      2 Covered, 1 Open
101      1 Covered, 1 Open
102      3 Covered, 2 Open
103      1 Covered, 1 Open
104      2 Covered, 2 Open
105      1 Covered, 1 Open
106                 5 Open
107      1 Covered, 1 Open
108      1 Covered, 1 Open
109      1 Covered, 1 Open
110      2 Covered, 2 Open
111      1 Covered, 1 Open
112      2 Covered, 2 Open
113      3 Covered, 2 Open
114      1 Covered, 1 Open
115      3 Covered, 2 Open
116      1 Covered, 1 Open
117      1 Covered, 1 Open
118      3 Covered, 3 Open
119      2 Covered, 2 Open
120                    NaN
121                    NaN
122                    NaN
123                    NaN
124                    NaN
125      3 Covered, 3 Open
126                    NaN
127                    NaN
128                    NaN
129                    NaN
130                    NaN
131                    NaN
132                    NaN
133                    NaN
134      1 Covered, 1 Open
135      3 Covered, 4 Open
136                    NaN
137                    NaN
138                    NaN
139                    NaN
140                    NaN
141                    NaN
142      1 Covered, 1 Open
143              2 Covered
144              1 Covered
145      1 Covered, 1 Open
146              2 Covered
147      1 Covered, 1 Open
148                 2 Open
149                    NaN
150      1 Covered, 1 Open
151      2 Covered, 1 Open
152      2 Covered, 2 Open
153      1 Covered, 2 Open
154      1 Covered, 2 Open
155      1 Covered, 1 Open
156      1 Covered, 1 Open
157                 1 Open
158      1 Covered, 1 Open
159      2 Covered, 2 Open
160      2 Covered, 4 Open
161                    NaN
162                    NaN
163      2 Covered, 2 Open
164              3 Covered
165      2 Covered, 2 Open
166      4 Covered, 4 Open
167      3 Covered, 2 Open
168      3 Covered, 3 Open
169      1 Covered, 2 Open
170      2 Covered, 2 Open
171      1 Covered, 1 Open
172              1 Covered
173                    NaN
174      1 Covered, 2 Open
175      1 Covered, 1 Open
176      1 Covered, 1 Open
177      1 Covered, 3 Open
178      1 Covered, 1 Open
179      1 Covered, 1 Open
180                 3 Open
181      2 Covered, 1 Open
182      1 Covered, 1 Open
183      1 Covered, 1 Open
184      1 Covered, 1 Open
185      4 Covered, 5 Open
186                    NaN
187      4 Covered, 2 Open
188      1 Covered, 1 Open
189              3 Covered
190      6 Covered, 7 Open
191              1 Covered
192      0 Covered, 0 Open
193      2 Covered, 2 Open
194                    NaN
195      2 Covered, 3 Open
196      2 Covered, 2 Open
197      2 Covered, 2 Open
198                    NaN
199      2 Covered, 2 Open
200      4 Covered, 4 Open
201      1 Covered, 1 Open
202      6 Covered, 4 Open
203      4 Covered, 6 Open
204      2 Covered, 2 Open
205      1 Covered, 1 Open
206      1 Covered, 1 Open
207                 2 Open
208      1 Covered, 1 Open
209      1 Covered, 1 Open
210      5 Covered, 4 Open
211      3 Covered, 2 Open
212      6 Covered, 4 Open
213      5 Covered, 4 Open
214      5 Covered, 4 Open
215      5 Covered, 4 Open
216      3 Covered, 2 Open
217      4 Covered, 4 Open
218      3 Covered, 4 Open
219      4 Covered, 3 Open
220      3 Covered, 3 Open
221      4 Covered, 3 Open
222      3 Covered, 3 Open
223      5 Covered, 4 Open
224      2 Covered, 2 Open
225      3 Covered, 4 Open
226      2 Covered, 2 Open
227      3 Covered, 2 Open
228      3 Covered, 3 Open
229      3 Covered, 3 Open
230      4 Covered, 5 Open
231      3 Covered, 3 Open
232      3 Covered, 3 Open
233      4 Covered, 3 Open
234      5 Covered, 5 Open
235      3 Covered, 2 Open
236      5 Covered, 3 Open
237      4 Covered, 4 Open
238                    NaN
239                    NaN
240                    NaN
241                    NaN
242                    NaN
243                    NaN
244                    NaN
245      1 Covered, 1 Open
246      1 Covered, 2 Open
247                    NaN
248                    NaN
249                    NaN
250                    NaN
251                    NaN
252                    NaN
253                    NaN
254                    NaN
255                    NaN
256                    NaN
257                    NaN
258                    NaN
259                    NaN
260      1 Covered, 1 Open
261      1 Covered, 1 Open
262      1 Covered, 1 Open
263      1 Covered, 1 Open
264                 2 Open
265                    NaN
266                 2 Open
267                    NaN
268      1 Covered, 2 Open
269                    NaN
270                    NaN
271      2 Covered, 3 Open
272                    NaN
273                 2 Open
274                 1 Open
275      1 Covered, 2 Open
276                    NaN
277                    NaN
278                 1 Open
279      2 Covered, 2 Open
280      2 Covered, 5 Open
281                 2 Open
282                    NaN
283                    NaN
284                 1 Open
285                 1 Open
286                 1 Open
287                    NaN
288      1 Covered, 2 Open
289                    NaN
290                    NaN
291                    NaN
292                    NaN
293                    NaN
294                    NaN
295                    NaN
296              2 Covered
297      2 Covered, 1 Open
298      2 Covered, 1 Open
299              2 Covered
300      2 Covered, 1 Open
301                    NaN
302      3 Covered, 4 Open
303      1 Covered, 2 Open
304      2 Covered, 1 Open
305      1 Covered, 3 Open
306      2 Covered, 2 Open
307                    NaN
308                    NaN
309                    NaN
310                    NaN
311      2 Covered, 2 Open
312                    NaN
313                    NaN
314      2 Covered, 2 Open
315      2 Covered, 1 Open
316      2 Covered, 1 Open
317      2 Covered, 2 Open
318                    NaN
319                    NaN
320                    NaN
321      3 Covered, 2 Open
322      2 Covered, 2 Open
323      2 Covered, 2 Open
324      2 Covered, 3 Open
325      2 Covered, 1 Open
326      2 Covered, 2 Open
327                    NaN
328                    NaN
329                    NaN
330              3 Covered
331      2 Covered, 4 Open
332      2 Covered, 1 Open
333      2 Covered, 2 Open
334                    NaN
335      2 Covered, 2 Open
336                    NaN
337                 2 Open
338      2 Covered, 1 Open
339      2 Covered, 2 Open
340      2 Covered, 2 Open
341      1 Covered, 2 Open
342      2 Covered, 1 Open
343      2 Covered, 3 Open
344      2 Covered, 3 Open
345      2 Covered, 2 Open
346      2 Covered, 2 Open
347      2 Covered, 1 Open
348      2 Covered, 2 Open
349      2 Covered, 1 Open
350      2 Covered, 1 Open
351      2 Covered, 4 Open
352      2 Covered, 2 Open
353                    NaN
354                    NaN
355                    NaN
356                    NaN
357                    NaN
358                    NaN
359                    NaN
360                    NaN
361                    NaN
362                    NaN
363                    NaN
364                    NaN
365                 4 Open
366                    NaN
367                    NaN
368                    NaN
369                    NaN
370                    NaN
371                    NaN
372                    NaN
373                    NaN
374                    NaN
375                    NaN
376                    NaN
377                    NaN
378                    NaN
379                    NaN
380                    NaN
381                    NaN
382                    NaN
383                    NaN
384                    NaN
385                    NaN
386                    NaN
387                    NaN
388                    NaN
389                    NaN
390                    NaN
391                    NaN
392                    NaN
393                    NaN
394                    NaN
395                    NaN
396                    NaN
397                    NaN
398                    NaN
399                    NaN
400      1 Covered, 1 Open
401      3 Covered, 2 Open
402      1 Covered, 1 Open
403      1 Covered, 1 Open
404              1 Covered
405                    NaN
406                    NaN
407                    NaN
408                    NaN
409                    NaN
410                    NaN
411                    NaN
412                    NaN
413                    NaN
414                    NaN
415                    NaN
416                    NaN
417                    NaN
418                    NaN
419                    NaN
420                    NaN
421                    NaN
422                    NaN
423                    NaN
424                    NaN
425                    NaN
426                    NaN
427                    NaN
428                    NaN
429                    NaN
430                    NaN
431                    NaN
432                    NaN
433                    NaN
434                    NaN
435                    NaN
436                    NaN
437                    NaN
438                    NaN
439                    NaN
440                    NaN
441              1 Covered
442                    NaN
443                    NaN
444                    NaN
445      1 Covered, 1 Open
446      1 Covered, 1 Open
447      1 Covered, 1 Open
448      2 Covered, 3 Open
449      1 Covered, 2 Open
450      2 Covered, 2 Open
451      0 Covered, 3 Open
452                 3 Open
453                 2 Open
454      0 Covered, 2 Open
455                    NaN
456      0 Covered, 3 Open
457                 3 Open
458      3 Covered, 3 Open
459                 2 Open
460                 1 Open
461      1 Covered, 1 Open
462      1 Covered, 1 Open
463      1 Covered, 1 Open
464      1 Covered, 1 Open
465              1 Covered
466                    NaN
467      2 Covered, 2 Open
468      3 Covered, 3 Open
469      3 Covered, 3 Open
470      3 Covered, 3 Open
471      3 Covered, 3 Open
472      3 Covered, 3 Open
473      3 Covered, 3 Open
474      3 Covered, 3 Open
475      3 Covered, 3 Open
476      3 Covered, 3 Open
477      3 Covered, 3 Open
478      3 Covered, 3 Open
479      3 Covered, 3 Open
480      3 Covered, 3 Open
481      3 Covered, 3 Open
482      3 Covered, 3 Open
483      3 Covered, 3 Open
484      3 Covered, 3 Open
485      3 Covered, 3 Open
486      3 Covered, 3 Open
487      3 Covered, 3 Open
488      3 Covered, 3 Open
489      3 Covered, 3 Open
490      3 Covered, 3 Open
491      3 Covered, 3 Open
492      3 Covered, 3 Open
493      3 Covered, 3 Open
494      3 Covered, 3 Open
495      3 Covered, 3 Open
496      3 Covered, 3 Open
497      3 Covered, 3 Open
498      3 Covered, 3 Open
499      3 Covered, 3 Open
500      3 Covered, 3 Open
501      3 Covered, 3 Open
502      4 Covered, 4 Open
503      3 Covered, 3 Open
504      4 Covered, 4 Open
505      3 Covered, 3 Open
506      3 Covered, 3 Open
507      3 Covered, 3 Open
508      4 Covered, 4 Open
509      3 Covered, 3 Open
510      4 Covered, 4 Open
511      3 Covered, 3 Open
512      4 Covered, 4 Open
513      4 Covered, 4 Open
514      4 Covered, 4 Open
515      3 Covered, 3 Open
516      4 Covered, 4 Open
517      4 Covered, 4 Open
518      3 Covered, 3 Open
519      4 Covered, 4 Open
520      4 Covered, 4 Open
521      4 Covered, 4 Open
522      4 Covered, 4 Open
523      4 Covered, 4 Open
524      4 Covered, 4 Open
525      4 Covered, 4 Open
526      4 Covered, 4 Open
527      4 Covered, 4 Open
528      3 Covered, 3 Open
529      4 Covered, 4 Open
530      4 Covered, 4 Open
531      3 Covered, 3 Open
532      3 Covered, 3 Open
533      3 Covered, 3 Open
534      3 Covered, 3 Open
535      3 Covered, 3 Open
536      3 Covered, 4 Open
537      3 Covered, 3 Open
538      3 Covered, 3 Open
539      3 Covered, 4 Open
540              1 Covered
541      3 Covered, 3 Open
542      3 Covered, 3 Open
543      3 Covered, 3 Open
544      3 Covered, 3 Open
545      3 Covered, 3 Open
546      1 Covered, 1 Open
547      1 Covered, 1 Open
548      1 Covered, 1 Open
549      1 Covered, 1 Open
550      1 Covered, 1 Open
551      1 Covered, 1 Open
552      1 Covered, 1 Open
553      2 Covered, 2 Open
554      1 Covered, 1 Open
555      1 Covered, 2 Open
556      1 Covered, 1 Open
557      1 Covered, 1 Open
558      1 Covered, 2 Open
559      1 Covered, 2 Open
560      1 Covered, 1 Open
561      2 Covered, 3 Open
562      1 Covered, 1 Open
563      1 Covered, 1 Open
564      1 Covered, 1 Open
565      1 Covered, 2 Open
566      4 Covered, 4 Open
567      2 Covered, 2 Open
568      2 Covered, 3 Open
569      1 Covered, 2 Open
570      1 Covered, 1 Open
571      1 Covered, 1 Open
572      1 Covered, 1 Open
573      1 Covered, 1 Open
574      1 Covered, 2 Open
575              2 Covered
576      2 Covered, 2 Open
577      3 Covered, 4 Open
578      2 Covered, 2 Open
579      2 Covered, 2 Open
580                    NaN
581      2 Covered, 1 Open
582      2 Covered, 2 Open
583      1 Covered, 1 Open
584      2 Covered, 3 Open
585      1 Covered, 1 Open
586      2 Covered, 2 Open
587      2 Covered, 3 Open
588      1 Covered, 1 Open
589      1 Covered, 1 Open
590      1 Covered, 1 Open
591      2 Covered, 2 Open
592      2 Covered, 1 Open
593      2 Covered, 1 Open
594      1 Covered, 1 Open
595      1 Covered, 1 Open
596      1 Covered, 1 Open
597      0 Covered, 1 Open
598      3 Covered, 2 Open
599      3 Covered, 2 Open
600      3 Covered, 2 Open
601      1 Covered, 1 Open
602      1 Covered, 1 Open
603      2 Covered, 1 Open
604      3 Covered, 2 Open
605                    NaN
606      2 Covered, 2 Open
607      3 Covered, 2 Open
608      2 Covered, 2 Open
609      1 Covered, 2 Open
610      2 Covered, 2 Open
611      3 Covered, 2 Open
612      2 Covered, 1 Open
613      4 Covered, 2 Open
614      3 Covered, 1 Open
615                 2 Open
616                 2 Open
617      1 Covered, 1 Open
618      1 Covered, 1 Open
619                 2 Open
620      2 Covered, 2 Open
621      2 Covered, 2 Open
622      2 Covered, 2 Open
623      3 Covered, 2 Open
624      3 Covered, 3 Open
625      2 Covered, 2 Open
626      4 Covered, 2 Open
627      3 Covered, 1 Open
628      1 Covered, 1 Open
629      2 Covered, 1 Open
630      5 Covered, 3 Open
631      2 Covered, 2 Open
632      3 Covered, 2 Open
633      3 Covered, 2 Open
634      2 Covered, 1 Open
635      4 Covered, 2 Open
636      3 Covered, 2 Open
637      1 Covered, 2 Open
638                 2 Open
639      1 Covered, 1 Open
640      1 Covered, 1 Open
641      1 Covered, 1 Open
642      1 Covered, 1 Open
643      1 Covered, 1 Open
644      1 Covered, 1 Open
645                 1 Open
646                 1 Open
647                    NaN
648      6 Covered, 4 Open
649      5 Covered, 2 Open
650      4 Covered, 2 Open
651      6 Covered, 2 Open
652      2 Covered, 2 Open
653      2 Covered, 2 Open
655      2 Covered, 2 Open
656      2 Covered, 2 Open
657      2 Covered, 2 Open
658      2 Covered, 2 Open
659      4 Covered, 2 Open
660      2 Covered, 2 Open
661      2 Covered, 2 Open
662      2 Covered, 2 Open
663      3 Covered, 2 Open
664      2 Covered, 2 Open
665      3 Covered, 3 Open
666      2 Covered, 3 Open
667      4 Covered, 2 Open
668      2 Covered, 2 Open
669      2 Covered, 2 Open
670      2 Covered, 2 Open
671      2 Covered, 2 Open
672      2 Covered, 2 Open
673      2 Covered, 2 Open
674      3 Covered, 2 Open
675      2 Covered, 2 Open
676      2 Covered, 2 Open
677      3 Covered, 2 Open
678                 1 Open
679                 1 Open
680                 1 Open
681                 1 Open
682                 1 Open
683                 1 Open
684                 1 Open
685      1 Covered, 1 Open
686      3 Covered, 2 Open
687      3 Covered, 2 Open
688      2 Covered, 2 Open
689      2 Covered, 2 Open
690      2 Covered, 2 Open
691      2 Covered, 2 Open
692      1 Covered, 1 Open
693      3 Covered, 2 Open
694      5 Covered, 3 Open
695      4 Covered, 2 Open
696      2 Covered, 1 Open
697      2 Covered, 2 Open
698      2 Covered, 2 Open
699      3 Covered, 1 Open
700      4 Covered, 2 Open
701      2 Covered, 1 Open
702      4 Covered, 2 Open
703      5 Covered, 2 Open
704      3 Covered, 2 Open
705      2 Covered, 1 Open
706      2 Covered, 2 Open
707      4 Covered, 2 Open
708      1 Covered, 2 Open
709      3 Covered, 2 Open
710      4 Covered, 2 Open
711      4 Covered, 4 Open
712      2 Covered, 1 Open
713      2 Covered, 2 Open
714      2 Covered, 1 Open
715      2 Covered, 1 Open
716      5 Covered, 2 Open
717      3 Covered, 3 Open
718      2 Covered, 3 Open
719      2 Covered, 2 Open
720      3 Covered, 2 Open
721      5 Covered, 2 Open
722      4 Covered, 3 Open
723      3 Covered, 2 Open
724      3 Covered, 3 Open
725      2 Covered, 2 Open
726      2 Covered, 1 Open
727      4 Covered, 2 Open
728      5 Covered, 2 Open
729      3 Covered, 1 Open
730      3 Covered, 2 Open
731      2 Covered, 2 Open
732      4 Covered, 2 Open
733      2 Covered, 2 Open
734      2 Covered, 3 Open
735      2 Covered, 1 Open
736      2 Covered, 2 Open
737      2 Covered, 2 Open
738      3 Covered, 2 Open
739      3 Covered, 2 Open
740      2 Covered, 1 Open

In [174]:
def park_func(x):
    Covered = 0
    Open = 0
    if pd.notna(x):
        temp = x.split(',')
        if len(temp) >= 2:
            # Covered
            cov_tmp = temp[0].strip().split(' ')
            if cov_tmp[0].isnumeric():
                Covered = int(cov_tmp[0])
                
            # Open
            open_tmp = temp[-1].strip().split(' ')
            if open_tmp[0].isnumeric():
                Open = int(open_tmp[0])
        else:
            if temp[0].split(' ')[0].isnumeric():
                if 'Covered' in temp[0]:
                    Covered = temp[0].split(' ')[0]
                else:
                    Open = temp[0].split(' ')[0]
    return Covered,Open

In [175]:
df['Parking'].apply(park_func)

0        (3, 3)
1        (1, 1)
2        (0, 0)
3        (1, 1)
4        (1, 1)
5        (2, 1)
6        (2, 2)
7        (0, 2)
8        (0, 0)
9        (0, 0)
10       (1, 1)
11       (0, 1)
12       (0, 0)
13       (0, 0)
14       (0, 4)
15       (1, 2)
16       (1, 1)
17       (1, 0)
18       (0, 0)
19       (0, 2)
20       (0, 0)
21       (1, 1)
22       (0, 1)
23       (1, 0)
24       (0, 1)
25       (0, 0)
26       (2, 1)
27       (1, 1)
28       (1, 3)
29       (0, 0)
30       (0, 2)
31       (0, 6)
32       (0, 0)
33       (0, 0)
34       (1, 1)
35       (0, 1)
36       (0, 1)
37       (2, 4)
38       (0, 1)
39       (0, 0)
40       (1, 0)
41       (0, 0)
42       (1, 2)
43       (0, 0)
44       (1, 2)
45       (1, 0)
46       (2, 2)
47       (2, 2)
48       (0, 3)
49       (2, 2)
50       (2, 1)
51       (2, 2)
52       (2, 1)
53       (4, 3)
54       (2, 2)
55       (1, 2)
56       (2, 2)
57       (2, 4)
58       (2, 4)
59       (1, 1)
60       (1, 2)
61       (0, 0)
62       (1, 2)
63       (1, 1)
64       (2, 1)
65       (3, 3)
66       (0, 3)
67       (2, 3)
68       (1, 1)
69       (1, 1)
70       (0, 2)
71       (2, 4)
72      (2, 10)
73       (1, 3)
74       (2, 4)
75       (2, 4)
76       (2, 2)
77       (3, 2)
78       (2, 2)
79       (2, 2)
80       (3, 2)
81       (2, 6)
82       (4, 6)
83       (3, 3)
84       (2, 4)
85       (2, 4)
86       (0, 0)
87       (0, 4)
88       (0, 2)
89       (1, 2)
90       (1, 3)
91       (0, 3)
92       (0, 3)
93       (0, 2)
94       (0, 2)
95       (1, 3)
96       (1, 3)
97       (6, 7)
98       (0, 6)
99       (4, 4)
100      (2, 1)
101      (1, 1)
102      (3, 2)
103      (1, 1)
104      (2, 2)
105      (1, 1)
106      (0, 5)
107      (1, 1)
108      (1, 1)
109      (1, 1)
110      (2, 2)
111      (1, 1)
112      (2, 2)
113      (3, 2)
114      (1, 1)
115      (3, 2)
116      (1, 1)
117      (1, 1)
118      (3, 3)
119      (2, 2)
120      (0, 0)
121      (0, 0)
122      (0, 0)
123      (0, 0)
124      (0, 0)
125      (3, 3)
126      (0, 0)
127      (0, 0)
128      (0, 0)
129      (0, 0)
130      (0, 0)
131      (0, 0)
132      (0, 0)
133      (0, 0)
134      (1, 1)
135      (3, 4)
136      (0, 0)
137      (0, 0)
138      (0, 0)
139      (0, 0)
140      (0, 0)
141      (0, 0)
142      (1, 1)
143      (2, 0)
144      (1, 0)
145      (1, 1)
146      (2, 0)
147      (1, 1)
148      (0, 2)
149      (0, 0)
150      (1, 1)
151      (2, 1)
152      (2, 2)
153      (1, 2)
154      (1, 2)
155      (1, 1)
156      (1, 1)
157      (0, 1)
158      (1, 1)
159      (2, 2)
160      (2, 4)
161      (0, 0)
162      (0, 0)
163      (2, 2)
164      (3, 0)
165      (2, 2)
166      (4, 4)
167      (3, 2)
168      (3, 3)
169      (1, 2)
170      (2, 2)
171      (1, 1)
172      (1, 0)
173      (0, 0)
174      (1, 2)
175      (1, 1)
176      (1, 1)
177      (1, 3)
178      (1, 1)
179      (1, 1)
180      (0, 3)
181      (2, 1)
182      (1, 1)
183      (1, 1)
184      (1, 1)
185      (4, 5)
186      (0, 0)
187      (4, 2)
188      (1, 1)
189      (3, 0)
190      (6, 7)
191      (1, 0)
192      (0, 0)
193      (2, 2)
194      (0, 0)
195      (2, 3)
196      (2, 2)
197      (2, 2)
198      (0, 0)
199      (2, 2)
200      (4, 4)
201      (1, 1)
202      (6, 4)
203      (4, 6)
204      (2, 2)
205      (1, 1)
206      (1, 1)
207      (0, 2)
208      (1, 1)
209      (1, 1)
210      (5, 4)
211      (3, 2)
212      (6, 4)
213      (5, 4)
214      (5, 4)
215      (5, 4)
216      (3, 2)
217      (4, 4)
218      (3, 4)
219      (4, 3)
220      (3, 3)
221      (4, 3)
222      (3, 3)
223      (5, 4)
224      (2, 2)
225      (3, 4)
226      (2, 2)
227      (3, 2)
228      (3, 3)
229      (3, 3)
230      (4, 5)
231      (3, 3)
232      (3, 3)
233      (4, 3)
234      (5, 5)
235      (3, 2)
236      (5, 3)
237      (4, 4)
238      (0, 0)
239      (0, 0)
240      (0, 0)
241      (0, 0)
242      (0, 0)
243      (0, 0)
244      (0, 0)
245      (1, 1)
246      (1, 2)
247      (0, 0)
248      (0, 0)
249      (0, 0)
250      (0, 0)
251      (0, 0)
252      (0, 0)
253      (0, 0)
254      (0, 0)
255      (0, 0)
256      (0, 0)
257      (0, 0)
258      (0, 0)
259      (0, 0)
260      (1, 1)
261      (1, 1)
262      (1, 1)
263      (1, 1)
264      (0, 2)
265      (0, 0)
266      (0, 2)
267      (0, 0)
268      (1, 2)
269      (0, 0)
270      (0, 0)
271      (2, 3)
272      (0, 0)
273      (0, 2)
274      (0, 1)
275      (1, 2)
276      (0, 0)
277      (0, 0)
278      (0, 1)
279      (2, 2)
280      (2, 5)
281      (0, 2)
282      (0, 0)
283      (0, 0)
284      (0, 1)
285      (0, 1)
286      (0, 1)
287      (0, 0)
288      (1, 2)
289      (0, 0)
290      (0, 0)
291      (0, 0)
292      (0, 0)
293      (0, 0)
294      (0, 0)
295      (0, 0)
296      (2, 0)
297      (2, 1)
298      (2, 1)
299      (2, 0)
300      (2, 1)
301      (0, 0)
302      (3, 4)
303      (1, 2)
304      (2, 1)
305      (1, 3)
306      (2, 2)
307      (0, 0)
308      (0, 0)
309      (0, 0)
310      (0, 0)
311      (2, 2)
312      (0, 0)
313      (0, 0)
314      (2, 2)
315      (2, 1)
316      (2, 1)
317      (2, 2)
318      (0, 0)
319      (0, 0)
320      (0, 0)
321      (3, 2)
322      (2, 2)
323      (2, 2)
324      (2, 3)
325      (2, 1)
326      (2, 2)
327      (0, 0)
328      (0, 0)
329      (0, 0)
330      (3, 0)
331      (2, 4)
332      (2, 1)
333      (2, 2)
334      (0, 0)
335      (2, 2)
336      (0, 0)
337      (0, 2)
338      (2, 1)
339      (2, 2)
340      (2, 2)
341      (1, 2)
342      (2, 1)
343      (2, 3)
344      (2, 3)
345      (2, 2)
346      (2, 2)
347      (2, 1)
348      (2, 2)
349      (2, 1)
350      (2, 1)
351      (2, 4)
352      (2, 2)
353      (0, 0)
354      (0, 0)
355      (0, 0)
356      (0, 0)
357      (0, 0)
358      (0, 0)
359      (0, 0)
360      (0, 0)
361      (0, 0)
362      (0, 0)
363      (0, 0)
364      (0, 0)
365      (0, 4)
366      (0, 0)
367      (0, 0)
368      (0, 0)
369      (0, 0)
370      (0, 0)
371      (0, 0)
372      (0, 0)
373      (0, 0)
374      (0, 0)
375      (0, 0)
376      (0, 0)
377      (0, 0)
378      (0, 0)
379      (0, 0)
380      (0, 0)
381      (0, 0)
382      (0, 0)
383      (0, 0)
384      (0, 0)
385      (0, 0)
386      (0, 0)
387      (0, 0)
388      (0, 0)
389      (0, 0)
390      (0, 0)
391      (0, 0)
392      (0, 0)
393      (0, 0)
394      (0, 0)
395      (0, 0)
396      (0, 0)
397      (0, 0)
398      (0, 0)
399      (0, 0)
400      (1, 1)
401      (3, 2)
402      (1, 1)
403      (1, 1)
404      (1, 0)
405      (0, 0)
406      (0, 0)
407      (0, 0)
408      (0, 0)
409      (0, 0)
410      (0, 0)
411      (0, 0)
412      (0, 0)
413      (0, 0)
414      (0, 0)
415      (0, 0)
416      (0, 0)
417      (0, 0)
418      (0, 0)
419      (0, 0)
420      (0, 0)
421      (0, 0)
422      (0, 0)
423      (0, 0)
424      (0, 0)
425      (0, 0)
426      (0, 0)
427      (0, 0)
428      (0, 0)
429      (0, 0)
430      (0, 0)
431      (0, 0)
432      (0, 0)
433      (0, 0)
434      (0, 0)
435      (0, 0)
436      (0, 0)
437      (0, 0)
438      (0, 0)
439      (0, 0)
440      (0, 0)
441      (1, 0)
442      (0, 0)
443      (0, 0)
444      (0, 0)
445      (1, 1)
446      (1, 1)
447      (1, 1)
448      (2, 3)
449      (1, 2)
450      (2, 2)
451      (0, 3)
452      (0, 3)
453      (0, 2)
454      (0, 2)
455      (0, 0)
456      (0, 3)
457      (0, 3)
458      (3, 3)
459      (0, 2)
460      (0, 1)
461      (1, 1)
462      (1, 1)
463      (1, 1)
464      (1, 1)
465      (1, 0)
466      (0, 0)
467      (2, 2)
468      (3, 3)
469      (3, 3)
470      (3, 3)
471      (3, 3)
472      (3, 3)
473      (3, 3)
474      (3, 3)
475      (3, 3)
476      (3, 3)
477      (3, 3)
478      (3, 3)
479      (3, 3)
480      (3, 3)
481      (3, 3)
482      (3, 3)
483      (3, 3)
484      (3, 3)
485      (3, 3)
486      (3, 3)
487      (3, 3)
488      (3, 3)
489      (3, 3)
490      (3, 3)
491      (3, 3)
492      (3, 3)
493      (3, 3)
494      (3, 3)
495      (3, 3)
496      (3, 3)
497      (3, 3)
498      (3, 3)
499      (3, 3)
500      (3, 3)
501      (3, 3)
502      (4, 4)
503      (3, 3)
504      (4, 4)
505      (3, 3)
506      (3, 3)
507      (3, 3)
508      (4, 4)
509      (3, 3)
510      (4, 4)
511      (3, 3)
512      (4, 4)
513      (4, 4)
514      (4, 4)
515      (3, 3)
516      (4, 4)
517      (4, 4)
518      (3, 3)
519      (4, 4)
520      (4, 4)
521      (4, 4)
522      (4, 4)
523      (4, 4)
524      (4, 4)
525      (4, 4)
526      (4, 4)
527      (4, 4)
528      (3, 3)
529      (4, 4)
530      (4, 4)
531      (3, 3)
532      (3, 3)
533      (3, 3)
534      (3, 3)
535      (3, 3)
536      (3, 4)
537      (3, 3)
538      (3, 3)
539      (3, 4)
540      (1, 0)
541      (3, 3)
542      (3, 3)
543      (3, 3)
544      (3, 3)
545      (3, 3)
546      (1, 1)
547      (1, 1)
548      (1, 1)
549      (1, 1)
550      (1, 1)
551      (1, 1)
552      (1, 1)
553      (2, 2)
554      (1, 1)
555      (1, 2)
556      (1, 1)
557      (1, 1)
558      (1, 2)
559      (1, 2)
560      (1, 1)
561      (2, 3)
562      (1, 1)
563      (1, 1)
564      (1, 1)
565      (1, 2)
566      (4, 4)
567      (2, 2)
568      (2, 3)
569      (1, 2)
570      (1, 1)
571      (1, 1)
572      (1, 1)
573      (1, 1)
574      (1, 2)
575      (2, 0)
576      (2, 2)
577      (3, 4)
578      (2, 2)
579      (2, 2)
580      (0, 0)
581      (2, 1)
582      (2, 2)
583      (1, 1)
584      (2, 3)
585      (1, 1)
586      (2, 2)
587      (2, 3)
588      (1, 1)
589      (1, 1)
590      (1, 1)
591      (2, 2)
592      (2, 1)
593      (2, 1)
594      (1, 1)
595      (1, 1)
596      (1, 1)
597      (0, 1)
598      (3, 2)
599      (3, 2)
600      (3, 2)
601      (1, 1)
602      (1, 1)
603      (2, 1)
604      (3, 2)
605      (0, 0)
606      (2, 2)
607      (3, 2)
608      (2, 2)
609      (1, 2)
610      (2, 2)
611      (3, 2)
612      (2, 1)
613      (4, 2)
614      (3, 1)
615      (0, 2)
616      (0, 2)
617      (1, 1)
618      (1, 1)
619      (0, 2)
620      (2, 2)
621      (2, 2)
622      (2, 2)
623      (3, 2)
624      (3, 3)
625      (2, 2)
626      (4, 2)
627      (3, 1)
628      (1, 1)
629      (2, 1)
630      (5, 3)
631      (2, 2)
632      (3, 2)
633      (3, 2)
634      (2, 1)
635      (4, 2)
636      (3, 2)
637      (1, 2)
638      (0, 2)
639      (1, 1)
640      (1, 1)
641      (1, 1)
642      (1, 1)
643      (1, 1)
644      (1, 1)
645      (0, 1)
646      (0, 1)
647      (0, 0)
648      (6, 4)
649      (5, 2)
650      (4, 2)
651      (6, 2)
652      (2, 2)
653      (2, 2)
655      (2, 2)
656      (2, 2)
657      (2, 2)
658      (2, 2)
659      (4, 2)
660      (2, 2)
661      (2, 2)
662      (2, 2)
663      (3, 2)
664      (2, 2)
665      (3, 3)
666      (2, 3)
667      (4, 2)
668      (2, 2)
669      (2, 2)
670      (2, 2)
671      (2, 2)
672      (2, 2)
673      (2, 2)
674      (3, 2)
675      (2, 2)
676      (2, 2)
677      (3, 2)
678      (0, 1)
679      (0, 1)
680      (0, 1)
681      (0, 1)
682      (0, 1)
683      (0, 1)
684      (0, 1)
685      (1, 1)
686      (3, 2)
687      (3, 2)
688      (2, 2)
689      (2, 2)
690      (2, 2)
691      (2, 2)
692      (1, 1)
693      (3, 2)
694      (5, 3)
695      (4, 2)
696      (2, 1)
697      (2, 2)
698      (2, 2)
699      (3, 1)
700      (4, 2)
701      (2, 1)
702      (4, 2)
703      (5, 2)
704      (3, 2)
705      (2, 1)
706      (2, 2)
707      (4, 2)
708      (1, 2)
709      (3, 2)
710      (4, 2)
711      (4, 4)
712      (2, 1)
713      (2, 2)
714      (2, 1)
715      (2, 1)
716      (5, 2)
717      (3, 3)
718      (2, 3)
719      (2, 2)
720      (3, 2)
721      (5, 2)
722      (4, 3)
723      (3, 2)
724      (3, 3)
725      (2, 2)
726      (2, 1)
727      (4, 2)
728      (5, 2)
729      (3, 1)
730      (3, 2)
731      (2, 2)
732      (4, 2)
733      (2, 2)
734      (2, 3)
735      (2, 1)
736      (2, 2)
737      (2, 2)
738      (3, 2)
739      (3, 2)
740      (2, 1)
741      (3, 1)
742      (4, 2)
743      (2, 0)
744      (4, 4)
745      (4, 2)
746      (2, 2)
747      (2, 2)
748      (3, 2)
749      (2, 1)
750      (2, 2)
751      (2, 2)
752      (3, 2)
753      (2, 2)
754      (2, 2)
755      (2, 2)
756      (2, 2)
757      (2, 2)
758      (3, 2)
759      (1, 1)
760      (1, 1)
761      (2, 2)
762      (2, 1)
763      (2, 3)
764      (3, 3)
765      (3, 2)
766      (2, 2)
767      (4, 2)
768      (3, 3)
769      (4, 4)
770      (2, 2)
771      (2, 3)
772      (3, 2)
773      (2, 2)
774      (2, 2)
775      (2, 2)
776      (3, 3)
777      (2, 2)
778      (4, 2)
779      (2, 2)
780      (2, 2)
781      (2, 3)
782      (3, 3)
783      (2, 2)
784      (2, 2)
785      (2, 2)
786      (2, 2)
787      (2, 2)
788      (3, 2)
789      (2, 2)
790      (2, 2)
791      (2, 2)
792      (2, 2)
793      (2, 2)
794      (3, 0)
795      (3, 2)
796      (2, 0)
797      (2, 2)
798      (3, 0)
799      (3, 0)
800      (2, 2)
801      (1, 2)
802      (2, 2)
803      (1, 2)
804      (3, 3)
805      (1, 2)
806      (2, 2)
807      (2, 2)
808      (3, 2)
809      (3, 2)
810      (5, 3)
811      (2, 2)
812      (2, 2)
813      (2, 2)
814      (2, 2)
815      (2, 2)
816      (2, 2)
817      (2, 2)
818      (2, 2)
819      (2, 2)
820      (4, 3)
821      (2, 2)
822      (2, 2)
823      (2, 2)
824      (5, 2)
825      (3, 2)
826      (2, 2)
827      (2, 2)
828      (2, 2)
829      (3, 2)
830      (2, 2)
831      (3, 2)
832      (2, 2)
833      (2, 2)
834      (2, 2)
835      (2, 2)
836      (2, 2)
837      (2, 2)
838      (4, 2)
839      (2, 2)
840      (2, 2)
841      (6, 4)
842      (5, 5)
843      (4, 2)
844      (3, 2)
845      (2, 2)
846      (2, 1)
847      (6, 5)
848      (3, 3)
849      (3, 3)
850      (4, 4)
851      (3, 3)
852      (3, 3)
853      (2, 2)
854      (2, 3)
855      (1, 2)
856      (3, 2)
857      (3, 2)
858      (2, 2)
859      (2, 2)
860      (3, 2)
861      (2, 2)
862      (2, 1)
863      (2, 2)
864      (2, 2)
865      (2, 2)
866      (2, 2)
867      (2, 2)
868      (2, 2)
869      (3, 2)
870      (3, 2)
871      (2, 2)
872      (2, 2)
873      (2, 2)
874      (5, 3)
875      (2, 2)
876      (2, 2)
877      (2, 2)
878      (2, 2)
879      (3, 2)
880      (3, 2)
881      (3, 2)
882      (2, 2)
883      (2, 2)
884      (2, 2)
885      (2, 2)
886      (1, 2)
887      (3, 2)
888      (2, 2)
889      (2, 2)
890      (2, 2)
891      (6, 3)
892      (5, 2)
893      (2, 2)
894      (6, 3)
895      (6, 2)
896      (6, 4)
897      (2, 2)
898      (2, 2)
899      (2, 2)
900      (2, 2)
901      (4, 2)
902      (2, 2)
903      (2, 3)
904      (2, 2)
905      (2, 2)
906      (2, 2)
907      (2, 2)
908      (2, 2)
909      (2, 2)
910      (2, 2)
911      (2, 2)
912      (2, 2)
913      (2, 2)
914      (2, 2)
915      (2, 2)
916      (1, 2)
917      (2, 2)
918      (2, 2)
919      (3, 2)
920      (2, 2)
921      (3, 2)
922      (3, 2)
923      (2, 2)
924      (2, 2)
925      (3, 2)
926      (2, 2)
927      (2, 2)
928      (2, 2)
929      (3, 3)
930      (2, 2)
931      (2, 2)
932      (3, 0)
933      (3, 2)
934      (1, 2)
935      (3, 2)
936      (2, 2)
937      (4, 3)
938      (2, 2)
939      (2, 2)
940      (2, 2)
941      (2, 2)
942      (3, 2)
943      (2, 2)
944      (2, 2)
945      (2, 2)
946      (2, 2)
947      (2, 2)
948      (0, 2)
949      (2, 2)
950      (0, 4)
951      (1, 2)
952      (0, 2)
953      (2, 2)
954      (0, 2)
955      (0, 2)
956      (2, 2)
957      (1, 2)
958      (1, 2)
959      (0, 2)
960      (2, 2)
961      (2, 2)
962      (1, 2)
963      (2, 2)
964      (0, 2)
965      (1, 2)
966      (1, 2)
967      (0, 2)
968      (2, 2)
969      (2, 2)
970      (1, 2)
971      (2, 2)
972      (2, 2)
973      (1, 2)
974      (1, 2)
975      (2, 4)
976      (1, 2)
977      (2, 2)
978      (1, 2)
979      (2, 2)
980      (1, 2)
981      (1, 2)
982      (1, 2)
983      (1, 1)
984      (2, 2)
985      (2, 2)
986      (2, 2)
987      (2, 2)
988      (1, 0)
989      (2, 2)
990      (2, 2)
991      (1, 2)
992      (0, 2)
993      (2, 2)
994      (1, 2)
995      (2, 2)
996      (2, 3)
997      (2, 2)
998      (1, 1)
999      (2, 2)
1000     (2, 2)
1001     (2, 2)
1002     (2, 2)
1003     (2, 2)
1004     (1, 1)
1005     (1, 2)
1006     (1, 1)
1007     (2, 2)
1008     (1, 2)
1009     (2, 2)
1010     (1, 2)
1011     (2, 2)
1012     (2, 2)
1013     (2, 2)
1014     (3, 3)
1015     (2, 2)
1016     (0, 0)
1017     (0, 1)
1018     (2, 2)
1019     (2, 2)
1020     (2, 3)
1021     (0, 1)
1022     (0, 1)
1023     (2, 2)
1024     (2, 2)
1025     (2, 3)
1026     (0, 1)
1027     (0, 1)
1028     (2, 2)
1029     (2, 2)
1030     (2, 2)
1031     (2, 2)
1032     (1, 2)
1033     (2, 2)
1034     (0, 2)
1035     (2, 2)
1036     (2, 2)
1037     (0, 0)
1038     (2, 2)
1039     (2, 2)
1040     (2, 2)
1041     (0, 0)
1042     (2, 2)
1043     (2, 2)
1044     (2, 2)
1045     (2, 2)
1046     (2, 2)
1047     (0, 1)
1048     (2, 2)
1049     (0, 1)
1050     (2, 2)
1051     (0, 2)
1052     (1, 2)
1053     (1, 1)
1054     (2, 2)
1055     (0, 2)
1056     (0, 2)
1057     (2, 2)
1058     (1, 2)
1059     (2, 2)
1060     (1, 2)
1061     (1, 2)
1062     (1, 2)
1063     (2, 2)
1064     (2, 0)
1065     (2, 1)
1066     (0, 0)
1067     (0, 1)
1068     (2, 0)
1069     (3, 3)
1070     (1, 1)
1071     (1, 0)
1072     (3, 3)
1073     (2, 2)
1074     (4, 4)
1075     (1, 1)
1076     (1, 1)
1077     (0, 1)
1078     (2, 2)
1079     (1, 2)
1080     (2, 2)
1081     (1, 1)
1082     (0, 2)
1083     (3, 2)
1084     (1, 2)
1085     (1, 1)
1086     (1, 1)
1087     (4, 4)
1088     (1, 3)
1089     (1, 0)
1090     (2, 0)
1091     (0, 5)
1092     (2, 2)
1093     (0, 6)
1094     (1, 2)
1095     (0, 0)
1096     (0, 0)
1097     (0, 1)
1098     (1, 1)
1099     (0, 0)
1100     (1, 3)
1101     (0, 0)
1102     (0, 0)
1103     (1, 0)
1104     (0, 1)
1105     (1, 0)
1107     (0, 0)
1108     (0, 0)
1109     (0, 1)
1110     (1, 1)
1111     (4, 4)
1112     (0, 2)
1113     (0, 0)
1114     (1, 1)
1115     (1, 2)
1116     (0, 2)
1117     (0, 0)
1118     (0, 0)
1119     (0, 1)
1120     (0, 1)
1121     (0, 2)
1122     (1, 0)
1123     (1, 2)
1124     (2, 1)
1125     (0, 0)
1126     (0, 0)
1127     (1, 1)
1128     (2, 2)
1129     (0, 0)
1130     (1, 1)
1131     (2, 2)
1132     (0, 0)
1133     (0, 0)
1134     (0, 1)
1135     (0, 2)
1136     (0, 2)
1137     (0, 0)
1138     (0, 1)
1139     (1, 1)
1140     (0, 0)
1141     (1, 1)
1142     (0, 0)
1143     (0, 0)
1144     (0, 2)
1145     (1, 1)
1146     (1, 1)
1147     (0, 0)
1148     (1, 1)
1149     (0, 4)
1150     (2, 3)
1151     (1, 4)
1152     (0, 0)
1153     (0, 1)
1154     (1, 1)
1155     (0, 0)
1156     (1, 0)
1157     (1, 2)
1158     (0, 0)
1159     (0, 1)
1160     (0, 0)
1161     (1, 0)
1162     (0, 0)
1163     (0, 0)
1164     (0, 0)
1165     (4, 4)
1166     (0, 0)
1167     (1, 2)
1168     (0, 0)
1169     (0, 0)
1170     (1, 0)
1171     (0, 0)
1172     (1, 1)
1173     (0, 0)
1174     (0, 2)
1175     (1, 2)
1176     (0, 0)
1177     (1, 0)
1178     (1, 1)
1179     (0, 1)
1180     (0, 0)
1181     (0, 2)
1182     (1, 2)
1183     (1, 0)
1184     (0, 0)
1185     (1, 0)
1186     (0, 0)
1187     (2, 0)
1188     (0, 0)
1189     (0, 1)
1190     (0, 0)
1191     (0, 0)
1192     (3, 0)
1193     (0, 1)
1194     (0, 0)
1195     (1, 2)
1196     (1, 0)
1197     (1, 0)
1198     (0, 1)
1199     (2, 2)
1200     (0, 2)
1201     (1, 0)
1202     (1, 1)
1203     (0, 2)
1204     (0, 1)
1205    (10, 0)
1206     (2, 3)
1207     (0, 0)
Name: Parking, dtype: object

In [176]:
parking_df = df['Parking'].apply(park_func).apply(pd.Series)
parking_df.columns = ['CoveredParking', 'OpenParking']
parking_df

     CoveredParking OpenParking
0                 3           3
1                 1           1
2                 0           0
3                 1           1
4                 1           1
5                 2           1
6                 2           2
7                 0           2
8                 0           0
9                 0           0
10                1           1
11                0           1
12                0           0
13                0           0
14                0           4
15                1           2
16                1           1
17                1           0
18                0           0
19                0           2
20                0           0
21                1           1
22                0           1
23                1           0
24                0           1
25                0           0
26                2           1
27                1           1
28                1           3
29                0           0
30                0           2
31                0           6
32                0           0
33                0           0
34                1           1
35                0           1
36                0           1
37                2           4
38                0           1
39                0           0
40                1           0
41                0           0
42                1           2
43                0           0
44                1           2
45                1           0
46                2           2
47                2           2
48                0           3
49                2           2
50                2           1
51                2           2
52                2           1
53                4           3
54                2           2
55                1           2
56                2           2
57                2           4
58                2           4
59                1           1
60                1           2
61                0           0
62                1           2
63                1           1
64                2           1
65                3           3
66                0           3
67                2           3
68                1           1
69                1           1
70                0           2
71                2           4
72                2          10
73                1           3
74                2           4
75                2           4
76                2           2
77                3           2
78                2           2
79                2           2
80                3           2
81                2           6
82                4           6
83                3           3
84                2           4
85                2           4
86                0           0
87                0           4
88                0           2
89                1           2
90                1           3
91                0           3
92                0           3
93                0           2
94                0           2
95                1           3
96                1           3
97                6           7
98                0           6
99                4           4
100               2           1
101               1           1
102               3           2
103               1           1
104               2           2
105               1           1
106               0           5
107               1           1
108               1           1
109               1           1
110               2           2
111               1           1
112               2           2
113               3           2
114               1           1
115               3           2
116               1           1
117               1           1
118               3           3
119               2           2
120               0           0
121               0           0
122               0           0
123               0           0
124               0           0
125               3           3
126               0           0
127               0           0
128               0           0
129               0           0
130               0           0
131               0           0
132               0           0
133               0           0
134               1           1
135               3           4
136               0           0
137               0           0
138               0           0
139               0           0
140               0           0
141               0           0
142               1           1
143               2           0
144               1           0
145               1           1
146               2           0
147               1           1
148               0           2
149               0           0
150               1           1
151               2           1
152               2           2
153               1           2
154               1           2
155               1           1
156               1           1
157               0           1
158               1           1
159               2           2
160               2           4
161               0           0
162               0           0
163               2           2
164               3           0
165               2           2
166               4           4
167               3           2
168               3           3
169               1           2
170               2           2
171               1           1
172               1           0
173               0           0
174               1           2
175               1           1
176               1           1
177               1           3
178               1           1
179               1           1
180               0           3
181               2           1
182               1           1
183               1           1
184               1           1
185               4           5
186               0           0
187               4           2
188               1           1
189               3           0
190               6           7
191               1           0
192               0           0
193               2           2
194               0           0
195               2           3
196               2           2
197               2           2
198               0           0
199               2           2
200               4           4
201               1           1
202               6           4
203               4           6
204               2           2
205               1           1
206               1           1
207               0           2
208               1           1
209               1           1
210               5           4
211               3           2
212               6           4
213               5           4
214               5           4
215               5           4
216               3           2
217               4           4
218               3           4
219               4           3
220               3           3
221               4           3
222               3           3
223               5           4
224               2           2
225               3           4
226               2           2
227               3           2
228               3           3
229               3           3
230               4           5
231               3           3
232               3           3
233               4           3
234               5           5
235               3           2
236               5           3
237               4           4
238               0           0
239               0           0
240               0           0
241               0           0
242               0           0
243               0           0
244               0           0
245               1           1
246               1           2
247               0           0
248               0           0
249               0           0
250               0           0
251               0           0
252               0           0
253               0           0
254               0           0
255               0           0
256               0           0
257               0           0
258               0           0
259               0           0
260               1           1
261               1           1
262               1           1
263               1           1
264               0           2
265               0           0
266               0           2
267               0           0
268               1           2
269               0           0
270               0           0
271               2           3
272               0           0
273               0           2
274               0           1
275               1           2
276               0           0
277               0           0
278               0           1
279               2           2
280               2           5
281               0           2
282               0           0
283               0           0
284               0           1
285               0           1
286               0           1
287               0           0
288               1           2
289               0           0
290               0           0
291               0           0
292               0           0
293               0           0
294               0           0
295               0           0
296               2           0
297               2           1
298               2           1
299               2           0
300               2           1
301               0           0
302               3           4
303               1           2
304               2           1
305               1           3
306               2           2
307               0           0
308               0           0
309               0           0
310               0           0
311               2           2
312               0           0
313               0           0
314               2           2
315               2           1
316               2           1
317               2           2
318               0           0
319               0           0
320               0           0
321               3           2
322               2           2
323               2           2
324               2           3
325               2           1
326               2           2
327               0           0
328               0           0
329               0           0
330               3           0
331               2           4
332               2           1
333               2           2
334               0           0
335               2           2
336               0           0
337               0           2
338               2           1
339               2           2
340               2           2
341               1           2
342               2           1
343               2           3
344               2           3
345               2           2
346               2           2
347               2           1
348               2           2
349               2           1
350               2           1
351               2           4
352               2           2
353               0           0
354               0           0
355               0           0
356               0           0
357               0           0
358               0           0
359               0           0
360               0           0
361               0           0
362               0           0
363               0           0
364               0           0
365               0           4
366               0           0
367               0           0
368               0           0
369               0           0
370               0           0
371               0           0
372               0           0
373               0           0
374               0           0
375               0           0
376               0           0
377               0           0
378               0           0
379               0           0
380               0           0
381               0           0
382               0           0
383               0           0
384               0           0
385               0           0
386               0           0
387               0           0
388               0           0
389               0           0
390               0           0
391               0           0
392               0           0
393               0           0
394               0           0
395               0           0
396               0           0
397               0           0
398               0           0
399               0           0
400               1           1
401               3           2
402               1           1
403               1           1
404               1           0
405               0           0
406               0           0
407               0           0
408               0           0
409               0           0
410               0           0
411               0           0
412               0           0
413               0           0
414               0           0
415               0           0
416               0           0
417               0           0
418               0           0
419               0           0
420               0           0
421               0           0
422               0           0
423               0           0
424               0           0
425               0           0
426               0           0
427               0           0
428               0           0
429               0           0
430               0           0
431               0           0
432               0           0
433               0           0
434               0           0
435               0           0
436               0           0
437               0           0
438               0           0
439               0           0
440               0           0
441               1           0
442               0           0
443               0           0
444               0           0
445               1           1
446               1           1
447               1           1
448               2           3
449               1           2
450               2           2
451               0           3
452               0           3
453               0           2
454               0           2
455               0           0
456               0           3
457               0           3
458               3           3
459               0           2
460               0           1
461               1           1
462               1           1
463               1           1
464               1           1
465               1           0
466               0           0
467               2           2
468               3           3
469               3           3
470               3           3
471               3           3
472               3           3
473               3           3
474               3           3
475               3           3
476               3           3
477               3           3
478               3           3
479               3           3
480               3           3
481               3           3
482               3           3
483               3           3
484               3           3
485               3           3
486               3           3
487               3           3
488               3           3
489               3           3
490               3           3
491               3           3
492               3           3
493               3           3
494               3           3
495               3           3
496               3           3
497               3           3
498               3           3
499               3           3
500               3           3
501               3           3
502               4           4
503               3           3
504               4           4
505               3           3
506               3           3
507               3           3
508               4           4
509               3           3
510               4           4
511               3           3
512               4           4
513               4           4
514               4           4
515               3           3
516               4           4
517               4           4
518               3           3
519               4           4
520               4           4
521               4           4
522               4           4
523               4           4
524               4           4
525               4           4
526               4           4
527               4           4
528               3           3
529               4           4
530               4           4
531               3           3
532               3           3
533               3           3
534               3           3
535               3           3
536               3           4
537               3           3
538               3           3
539               3           4
540               1           0
541               3           3
542               3           3
543               3           3
544               3           3
545               3           3
546               1           1
547               1           1
548               1           1
549               1           1
550               1           1
551               1           1
552               1           1
553               2           2
554               1           1
555               1           2
556               1           1
557               1           1
558               1           2
559               1           2
560               1           1
561               2           3
562               1           1
563               1           1
564               1           1
565               1           2
566               4           4
567               2           2
568               2           3
569               1           2
570               1           1
571               1           1
572               1           1
573               1           1
574               1           2
575               2           0
576               2           2
577               3           4
578               2           2
579               2           2
580               0           0
581               2           1
582               2           2
583               1           1
584               2           3
585               1           1
586               2           2
587               2           3
588               1           1
589               1           1
590               1           1
591               2           2
592               2           1
593               2           1
594               1           1
595               1           1
596               1           1
597               0           1
598               3           2
599               3           2
600               3           2
601               1           1
602               1           1
603               2           1
604               3           2
605               0           0
606               2           2
607               3           2
608               2           2
609               1           2
610               2           2
611               3           2
612               2           1
613               4           2
614               3           1
615               0           2
616               0           2
617               1           1
618               1           1
619               0           2
620               2           2
621               2           2
622               2           2
623               3           2

In [177]:
df.insert(21,'OpenParking',value= parking_df['OpenParking'].values)

In [178]:
df.insert(21,'CoveredParking',value= parking_df['CoveredParking'].values)

In [179]:
df.drop(columns = 'Parking',inplace = True)

In [180]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,CoveredParking,OpenParking,RoadFacing,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,Independent House/Villa for Sale,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,Old,Marble,No,Semifurnished,3,3,40.0,"24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28.000
1,V75627519,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,Old,Others,No,Unfurnished,1,1,40.0,Municipal corporation,NaN,Yes,No,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14.000
2,P75122867,6Bedrooms 6Baths,Independent House/Villa for Sale,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,RelNew,NaN,No,NaN,0,0,NaN,NaN,NaN,NaN,No,We have a house/villa available for sale in mo...,[],NaN,2.500
3,W75661879,4Bedrooms 4Baths,Independent House/Villa for Sale,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Club,Main Road,Others,Park/Garden,Pool,Sea facing",New,Others,Yes,Furnished,1,1,NaN,24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.650
4,P75385469,3Bedrooms 3Baths,Independent House/Villa for Sale,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,UndConst,Ceramic,Yes,Semifurnished,1,1,30.0,Borewell/Tank,NaN,NaN,No,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",0.589

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1206 entries, 0 to 1207
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_id         1206 non-null   object
 1   property_name       1206 non-null   object
 2   property_type       1206 non-null   object
 3   link                1206 non-null   object
 4   Society             77 non-null     object
 5   address1            1206 non-null   object
 6   address2            1206 non-null   object
 7   PricePerUnit        1206 non-null   object
 8   area                1206 non-null   object
 9   area_unit           1206 non-null   object
 10  bedRoom             1206 non-null   int32
 11  bathroom            1206 non-null   int32
 12  balcony             1206 non-null   int32
 13  additionalRoom      802 non-null    object
 14  facing              859 non-null    object
 15  TotalFloors         1206 non-null   int32
 16  Overlooking         711 non-null    object
 17  agePossession       1206 non-null   object
 18  Flooring            765 non-null    object
 19  GatedCommunity      1206 non-null   object
 20  Furnishing          1053 non-null   object
 21  CoveredParking      1206 non-null   object
 22  OpenParking         1206 non-null   object
 23  RoadFacing          515 non-null    float64
 24  WaterSource         886 non-null    object
 25  PowerBackup         189 non-null    object
 26  WheelChairFriendly  388 non-null    object
 27  PetFriendly         1206 non-null   object
 28  description         1206 non-null   object
 29  furnishDetails      625 non-null    object
 30  features            931 non-null    object
 31  price               1206 non-null   float64
dtypes: float64(2), int32(4), object(26)
memory usage: 292.1+ KB

In [182]:
df['OpenParking'] = df['OpenParking'].astype(int)

In [183]:
df['CoveredParking'] = df['CoveredParking'].astype(int)

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1206 entries, 0 to 1207
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_id         1206 non-null   object
 1   property_name       1206 non-null   object
 2   property_type       1206 non-null   object
 3   link                1206 non-null   object
 4   Society             77 non-null     object
 5   address1            1206 non-null   object
 6   address2            1206 non-null   object
 7   PricePerUnit        1206 non-null   object
 8   area                1206 non-null   object
 9   area_unit           1206 non-null   object
 10  bedRoom             1206 non-null   int32
 11  bathroom            1206 non-null   int32
 12  balcony             1206 non-null   int32
 13  additionalRoom      802 non-null    object
 14  facing              859 non-null    object
 15  TotalFloors         1206 non-null   int32
 16  Overlooking         711 non-null    object
 17  agePossession       1206 non-null   object
 18  Flooring            765 non-null    object
 19  GatedCommunity      1206 non-null   object
 20  Furnishing          1053 non-null   object
 21  CoveredParking      1206 non-null   int32
 22  OpenParking         1206 non-null   int32
 23  RoadFacing          515 non-null    float64
 24  WaterSource         886 non-null    object
 25  PowerBackup         189 non-null    object
 26  WheelChairFriendly  388 non-null    object
 27  PetFriendly         1206 non-null   object
 28  description         1206 non-null   object
 29  furnishDetails      625 non-null    object
 30  features            931 non-null    object
 31  price               1206 non-null   float64
dtypes: float64(2), int32(6), object(24)
memory usage: 282.7+ KB

### PowerBackup

In [185]:
df['PowerBackup'].value_counts()

PowerBackup
Partial    99
Full       90
Name: count, dtype: int64

In [186]:
df['PowerBackup'].isna().sum()

1017

### Property Type

In [187]:
df['property_type'].value_counts()

property_type
Independent House/Villa for Sale    1206
Name: count, dtype: int64

In [188]:
def prop_type_func(x):
    if pd.notna(x):
        if x == 'Independent House/Villa for Sale':
            return 'House/Villa'
    else:
        return x

In [189]:
df['property_type'] = df['property_type'].apply(prop_type_func)

In [190]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,CoveredParking,OpenParking,RoadFacing,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,House/Villa,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,Old,Marble,No,Semifurnished,3,3,40.0,"24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28.000
1,V75627519,3Bedrooms 3Baths,House/Villa,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,Old,Others,No,Unfurnished,1,1,40.0,Municipal corporation,NaN,Yes,No,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14.000
2,P75122867,6Bedrooms 6Baths,House/Villa,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,RelNew,NaN,No,NaN,0,0,NaN,NaN,NaN,NaN,No,We have a house/villa available for sale in mo...,[],NaN,2.500
3,W75661879,4Bedrooms 4Baths,House/Villa,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Club,Main Road,Others,Park/Garden,Pool,Sea facing",New,Others,Yes,Furnished,1,1,NaN,24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.650
4,P75385469,3Bedrooms 3Baths,House/Villa,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,UndConst,Ceramic,Yes,Semifurnished,1,1,30.0,Borewell/Tank,NaN,NaN,No,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",0.589

### WheelChairFriendly

In [191]:
df['WheelChairFriendly'].value_counts()

WheelChairFriendly
Yes    388
Name: count, dtype: int64

In [192]:
df['WheelChairFriendly'].fillna('No',inplace = True)

In [193]:
df['WheelChairFriendly'].value_counts()

WheelChairFriendly
No     818
Yes    388
Name: count, dtype: int64

In [194]:
df.head()

,property_id,property_name,property_type,link,Society,address1,address2,PricePerUnit,area,area_unit,bedRoom,bathroom,balcony,additionalRoom,facing,TotalFloors,Overlooking,agePossession,Flooring,GatedCommunity,Furnishing,CoveredParking,OpenParking,RoadFacing,WaterSource,PowerBackup,WheelChairFriendly,PetFriendly,description,furnishDetails,features,price
0,R76627967,7Bedrooms 7Baths,House/Villa,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,"Sector 15 Chandigarh, Chandigarh, India","Sector 15 Chandigarh, Chandigarh, India","1,40,000 per sq.yards",Plot area 2000(1672.25 sq.m.) sq.yards,sq.yards,7,7,4,Servant Room,North-West,2,Others,Old,Marble,No,Semifurnished,3,3,40.0,"24*7 Water,Municipal corporation",NaN,Yes,Yes,This 7 bhk house for sale in sector 15 chandig...,"['4 Fan', '4 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Water purifi...",28.000
1,V75627519,3Bedrooms 3Baths,House/Villa,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Sector 11 Chandigarh, Chandigarh, India","Sector 11 Chandigarh, Chandigarh, India","2,80,000 per sq.yards",Plot area 500(418.06 sq.m.) sq.yards,sq.yards,3,3,2,Servant Room,South,1,Main Road,Old,Others,No,Unfurnished,1,1,40.0,Municipal corporation,NaN,Yes,No,Check out this 3 bhk house for sale in sector ...,NaN,"['False Ceiling Lighting', 'Separate entry for...",14.000
2,P75122867,6Bedrooms 6Baths,House/Villa,https://www.99acres.com/6-bhk-bedroom-independ...,Bajwa Sunny Urban Greens,"Bajwa Sunny Urban Greens, Mohali, Chandigarh, ...","Mohali, Chandigarh, India","6,944 per sq.ft.",Plot area 3600(334.45 sq.m.) sq.ft.,sq.ft.,6,6,2,NaN,South,2,NaN,RelNew,NaN,No,NaN,0,0,NaN,NaN,NaN,No,No,We have a house/villa available for sale in mo...,[],NaN,2.500
3,W75661879,4Bedrooms 4Baths,House/Villa,https://www.99acres.com/4-bhk-bedroom-independ...,Altura Apartments,"Altura Apartments, Zirakpur, Chandigarh, India","Zirakpur, Chandigarh, India",813 per sq.ft.,Plot area 22000(2043.87 sq.m.) sq.ft.,sq.ft.,4,4,4,"Pooja Room,Study Room,Servant Room,Others",NaN,2,"Club,Main Road,Others,Park/Garden,Pool,Sea facing",New,Others,Yes,Furnished,1,1,NaN,24*7 Water,Full,Yes,Yes,Penthouse with open bath tub very big terrace ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Feng Shui / Vaastu Compliant', 'Private Gard...",1.650
4,P75385469,3Bedrooms 3Baths,House/Villa,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,"Dera Bassi, Chandigarh, India","Dera Bassi, Chandigarh, India","52,589 per sq.yards",Plot area 112(93.65 sq.m.) sq.yards,sq.yards,3,3,1,NaN,North-West,2,Park/Garden,UndConst,Ceramic,Yes,Semifurnished,1,1,30.0,Borewell/Tank,NaN,No,No,Welcome to the epitome of comfortable living i...,"['16 Light', '1 Modular Kitchen', '1 Chimney',...","['Maintenance Staff', 'Water Storage', 'Park',...",0.589

In [195]:
#ind_chd_safe = df.copy()

In [196]:
#ind_pkl_safe = df.copy()

In [197]:
df.to_csv('data/clean/ind-house-chd-clean-v1.csv',index = False)